<?php

namespace Database\Seeders\Helpers;

use Illuminate\Database\Seeder;
use App\Models\Helpers\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['id' => '4', 'name' => 'Afeganistão', 'nationality' => 'Afegã', 'ddi' => '93'],
            ['id' => '8', 'name' => 'Albânia', 'nationality' => 'Albanesa', 'ddi' => '355'],
            ['id' => '10', 'name' => 'Antártida', 'nationality' => 'Antartida', 'ddi' => ''],
            ['id' => '12', 'name' => 'Argélia', 'nationality' => 'Argelina', 'ddi' => '213'],
            ['id' => '16', 'name' => 'Samoa Americana', 'nationality' => 'Samoana', 'ddi' => ''],
            ['id' => '20', 'name' => 'Andorra', 'nationality' => 'Andorrana', 'ddi' => '376'],
            ['id' => '24', 'name' => 'Angola', 'nationality' => 'Angolana', 'ddi' => '244'],
            ['id' => '28', 'name' => 'Antígua e Barbuda', 'nationality' => 'Antiguana', 'ddi' => ''],
            ['id' => '31', 'name' => 'Azerbaijão', 'nationality' => 'Azerbaijana', 'ddi' => '994'],
            ['id' => '32', 'name' => 'Argentina', 'nationality' => 'Argentina', 'ddi' => '54'],
            ['id' => '36', 'name' => 'Austrália', 'nationality' => 'Australiana', 'ddi' => '61'],
            ['id' => '40', 'name' => 'Áustria', 'nationality' => 'Austríaca', 'ddi' => '43'],
            ['id' => '44', 'name' => 'Bahamas', 'nationality' => 'Baamiana', 'ddi' => ''],
            ['id' => '48', 'name' => 'Bahrein', 'nationality' => 'Baremita', 'ddi' => '973'],
            ['id' => '50', 'name' => 'Bangladesh', 'nationality' => 'Bengali', 'ddi' => '880'],
            ['id' => '51', 'name' => 'Armênia', 'nationality' => 'Arménia', 'ddi' => '374'],
            ['id' => '52', 'name' => 'Barbados', 'nationality' => 'Barbadiana', 'ddi' => ''],
            ['id' => '56', 'name' => 'Bélgica', 'nationality' => 'Belga', 'ddi' => '32'],
            ['id' => '60', 'name' => 'Bermudas', 'nationality' => 'Bermudenha', 'ddi' => ''],
            ['id' => '64', 'name' => 'Butão', 'nationality' => 'Butanesa', 'ddi' => '975'],
            ['id' => '68', 'name' => 'Bolívia', 'nationality' => 'Boliviana', 'ddi' => '591'],
            ['id' => '70', 'name' => 'Bósnia e Herzegovina', 'nationality' => 'Bosnia', 'ddi' => ''],
            ['id' => '72', 'name' => 'Botswana', 'nationality' => 'Botsuana', 'ddi' => ''],
            ['id' => '74', 'name' => 'Ilha Bouvet', 'nationality' => '', 'ddi' => ''],
            ['id' => '76', 'name' => 'Brasil', 'nationality' => 'Brasileira', 'ddi' => '55'],
            ['id' => '84', 'name' => 'Belize', 'nationality' => 'Belizenha', 'ddi' => '501'],
            ['id' => '86', 'name' => 'Território Britânico do Oceano Índico', 'nationality' => '', 'ddi' => '246'],
            ['id' => '90', 'name' => 'Ilhas Salomão', 'nationality' => 'Salomônica', 'ddi' => '677'],
            ['id' => '92', 'name' => 'Ilhas Virgens Britânicas', 'nationality' => '', 'ddi' => ''],
            ['id' => '96', 'name' => 'Brunei', 'nationality' => 'Bruneana', 'ddi' => '673'],
            ['id' => '100', 'name' => 'Bulgária', 'nationality' => 'Búlgara', 'ddi' => '359'],
            ['id' => '104', 'name' => 'Myanmar', 'nationality' => 'Birmanesa', 'ddi' => ''],
            ['id' => '108', 'name' => 'Burundi', 'nationality' => 'Burundiana', 'ddi' => '257'],
            ['id' => '112', 'name' => 'Bielorrússia', 'nationality' => 'Bielorrussa', 'ddi' => ''],
            ['id' => '116', 'name' => 'Camboja', 'nationality' => 'Cambojana', 'ddi' => ''],
            ['id' => '120', 'name' => 'Camarões', 'nationality' => 'Camaronesa', 'ddi' => '237'],
            ['id' => '124', 'name' => 'Canadá', 'nationality' => 'Canadense', 'ddi' => '1'],
            ['id' => '132', 'name' => 'Cabo Verde', 'nationality' => 'Cabo-verdiana', 'ddi' => '238'],
            ['id' => '136', 'name' => 'Ilhas Cayman', 'nationality' => 'Caimanesa', 'ddi' => ''],
            ['id' => '140', 'name' => 'República Centro-Africana', 'nationality' => 'Centrafricano', 'ddi' => '236'],
            ['id' => '144', 'name' => 'Sri Lanka', 'nationality' => 'Cingalesa', 'ddi' => ''],
            ['id' => '148', 'name' => 'Chade', 'nationality' => 'Chadiense', 'ddi' => '235'],
            ['id' => '152', 'name' => 'Chile', 'nationality' => 'Chilena', 'ddi' => '56'],
            ['id' => '156', 'name' => 'China', 'nationality' => 'Chinesa', 'ddi' => '86'],
            ['id' => '158', 'name' => 'República da China', 'nationality' => 'Chinesa', 'ddi' => ''],
            ['id' => '162', 'name' => 'Ilhas Natal', 'nationality' => '', 'ddi' => ''],
            ['id' => '166', 'name' => 'Ilhas Cocos (Keeling]', 'nationality' => '', 'ddi' => ''],
            ['id' => '170', 'name' => 'Colômbia', 'nationality' => 'Colombiana', 'ddi' => '57'],
            ['id' => '174', 'name' => 'Comores', 'nationality' => 'Comorense', 'ddi' => ''],
            ['id' => '175', 'name' => 'Mayotte', 'nationality' => 'Maiotense', 'ddi' => '262'],
            ['id' => '178', 'name' => 'República do Congo', 'nationality' => 'Congolesa', 'ddi' => ''],
            ['id' => '180', 'name' => 'República Democrática do Congo', 'nationality' => 'Congolesa', 'ddi' => ''],
            ['id' => '184', 'name' => 'Ilhas Cook', 'nationality' => 'Cookense', 'ddi' => '682'],
            ['id' => '188', 'name' => 'Costa Rica', 'nationality' => 'Costa-riquenha', 'ddi' => '506'],
            ['id' => '191', 'name' => 'Croácia', 'nationality' => 'Croata', 'ddi' => '385'],
            ['id' => '192', 'name' => 'Cuba', 'nationality' => 'Cubana', 'ddi' => '53'],
            ['id' => '196', 'name' => 'Chipre', 'nationality' => 'Cipriota', 'ddi' => ''],
            ['id' => '203', 'name' => 'República Tcheca', 'nationality' => 'Tcheca', 'ddi' => '420'],
            ['id' => '204', 'name' => 'Benim', 'nationality' => 'Beninesea', 'ddi' => ''],
            ['id' => '208', 'name' => 'Dinamarca', 'nationality' => 'Dinamarquesa', 'ddi' => '45'],
            ['id' => '212', 'name' => 'Dominica', 'nationality' => 'Dominiquesa', 'ddi' => ''],
            ['id' => '214', 'name' => 'República Dominicana', 'nationality' => 'Dominicana', 'ddi' => ''],
            ['id' => '218', 'name' => 'Equador', 'nationality' => 'Equatoriana', 'ddi' => '593'],
            ['id' => '222', 'name' => 'El Salvador', 'nationality' => 'Salvadorenha', 'ddi' => ''],
            ['id' => '226', 'name' => 'Guiné Equatorial', 'nationality' => 'Guinéu-equatoriana', 'ddi' => '240'],
            ['id' => '231', 'name' => 'Etiópia', 'nationality' => 'Etíope', 'ddi' => '251'],
            ['id' => '232', 'name' => 'Eritreia', 'nationality' => 'Eritreu', 'ddi' => '291'],
            ['id' => '233', 'name' => 'Estônia', 'nationality' => 'Estoniana', 'ddi' => '372'],
            ['id' => '234', 'name' => 'Ilhas Feroe', 'nationality' => '', 'ddi' => ''],
            ['id' => '238', 'name' => 'Ilhas Malvinas', 'nationality' => '', 'ddi' => ''],
            ['id' => '239', 'name' => 'Ilhas Geórgia do Sul e Sandwich do Sul', 'nationality' => '', 'ddi' => ''],
            ['id' => '242', 'name' => 'Fiji', 'nationality' => 'Fjiana', 'ddi' => ''],
            ['id' => '246', 'name' => 'Finlândia', 'nationality' => 'Finlandesa', 'ddi' => '358'],
            ['id' => '248', 'name' => 'Ilhas Aland', 'nationality' => 'Alandesa', 'ddi' => ''],
            ['id' => '250', 'name' => 'França', 'nationality' => 'Francesa', 'ddi' => '33'],
            ['id' => '254', 'name' => 'Guiana Francesa', 'nationality' => 'Franco Guianêsa', 'ddi' => ''],
            ['id' => '258', 'name' => 'Polinésia Francesa', 'nationality' => 'Polinésia', 'ddi' => ''],
            ['id' => '260', 'name' => 'Terras Austrais e Antárticas Francesas', 'nationality' => '', 'ddi' => ''],
            ['id' => '262', 'name' => 'Djibouti', 'nationality' => 'Djibutiense', 'ddi' => ''],
            ['id' => '266', 'name' => 'Gabão', 'nationality' => 'Gabonesa', 'ddi' => ''],
            ['id' => '268', 'name' => 'Geórgia', 'nationality' => 'Georgiana', 'ddi' => '995'],
            ['id' => '270', 'name' => 'Gâmbia', 'nationality' => 'Gambiana', 'ddi' => '220'],
            ['id' => '275', 'name' => 'Palestina', 'nationality' => 'Palestina', 'ddi' => '970'],
            ['id' => '276', 'name' => 'Alemanha', 'nationality' => 'Alemã', 'ddi' => '49'],
            ['id' => '288', 'name' => 'Gana', 'nationality' => 'Ganesa', 'ddi' => '233'],
            ['id' => '292', 'name' => 'Gibraltar', 'nationality' => 'Gibraltina', 'ddi' => '350'],
            ['id' => '296', 'name' => 'Kiribati', 'nationality' => 'Quiribatiana', 'ddi' => '686'],
            ['id' => '300', 'name' => 'Grécia', 'nationality' => 'Grega', 'ddi' => '30'],
            ['id' => '304', 'name' => 'Groenlândia', 'nationality' => 'Groenlandesa', 'ddi' => '299'],
            ['id' => '308', 'name' => 'Granada', 'nationality' => 'Granadina', 'ddi' => ''],
            ['id' => '312', 'name' => 'Guadalupe', 'nationality' => 'Guadalupense', 'ddi' => ''],
            ['id' => '316', 'name' => 'Guam', 'nationality' => 'Guamesa', 'ddi' => ''],
            ['id' => '320', 'name' => 'Guatemala', 'nationality' => 'Guatemalteca', 'ddi' => '502'],
            ['id' => '324', 'name' => 'Guiné', 'nationality' => 'Guineana', 'ddi' => ''],
            ['id' => '328', 'name' => 'Guiana', 'nationality' => 'Guianense', 'ddi' => '592'],
            ['id' => '332', 'name' => 'Haiti ', 'nationality' => 'Haitiana', 'ddi' => ''],
            ['id' => '334', 'name' => 'Ilha Heard e Ilhas McDonald', 'nationality' => '', 'ddi' => ''],
            ['id' => '336', 'name' => 'Vaticano', 'nationality' => '', 'ddi' => ''],
            ['id' => '339', 'name' => 'Apátrida', 'nationality' => 'Apatrida', 'ddi' => ''],
            ['id' => '340', 'name' => 'Honduras', 'nationality' => 'Hondurenha', 'ddi' => '504'],
            ['id' => '344', 'name' => 'Hong Kong', 'nationality' => 'Honconguesa', 'ddi' => '852'],
            ['id' => '348', 'name' => 'Hungria', 'nationality' => 'Húngara', 'ddi' => '36'],
            ['id' => '352', 'name' => 'Islândia', 'nationality' => 'Islandesa', 'ddi' => '354'],
            ['id' => '356', 'name' => 'Índia ', 'nationality' => 'Indiana', 'ddi' => ''],
            ['id' => '360', 'name' => 'Indonésia', 'nationality' => 'Indonésia', 'ddi' => '62'],
            ['id' => '364', 'name' => 'Irã', 'nationality' => 'Iraniana', 'ddi' => '98'],
            ['id' => '368', 'name' => 'Iraque', 'nationality' => 'Iraquiana', 'ddi' => '964'],
            ['id' => '372', 'name' => 'Irlanda', 'nationality' => 'Irlandesa', 'ddi' => ''],
            ['id' => '376', 'name' => 'Israel', 'nationality' => 'Israelense', 'ddi' => '972'],
            ['id' => '380', 'name' => 'Itália', 'nationality' => 'Italiana', 'ddi' => '39'],
            ['id' => '384', 'name' => 'Costa do Marfim', 'nationality' => 'Marfiniana', 'ddi' => '225'],
            ['id' => '388', 'name' => 'Jamaica', 'nationality' => 'Jamaicana', 'ddi' => ''],
            ['id' => '392', 'name' => 'Japão', 'nationality' => 'Japonesa', 'ddi' => '81'],
            ['id' => '398', 'name' => 'Cazaquistão', 'nationality' => 'Cazaque', 'ddi' => '7'],
            ['id' => '400', 'name' => 'Jordânia', 'nationality' => 'Jordaniana', 'ddi' => '962'],
            ['id' => '404', 'name' => 'Quénia', 'nationality' => 'Queniana', 'ddi' => ''],
            ['id' => '408', 'name' => 'Coreia do Norte', 'nationality' => 'Norte-coreana', 'ddi' => '850'],
            ['id' => '410', 'name' => 'Coreia do Sul', 'nationality' => 'Sul-Coreana', 'ddi' => ''],
            ['id' => '414', 'name' => 'Kuwait ', 'nationality' => 'Kuwaitiana', 'ddi' => ''],
            ['id' => '417', 'name' => 'República Quirguiz', 'nationality' => 'Quirguiz', 'ddi' => ''],
            ['id' => '418', 'name' => 'Laos', 'nationality' => 'Laociana', 'ddi' => '856'],
            ['id' => '422', 'name' => 'Líbano', 'nationality' => 'Libanesa', 'ddi' => '961'],
            ['id' => '426', 'name' => 'Lesoto', 'nationality' => 'Lesotiana', 'ddi' => '266'],
            ['id' => '428', 'name' => 'Letónia', 'nationality' => 'Letã', 'ddi' => ''],
            ['id' => '430', 'name' => 'Libéria', 'nationality' => 'Liberiana', 'ddi' => '231'],
            ['id' => '434', 'name' => 'Líbia', 'nationality' => 'Líbia', 'ddi' => '218'],
            ['id' => '438', 'name' => 'Liechtenstein', 'nationality' => 'Liechtensteinense', 'ddi' => '423'],
            ['id' => '440', 'name' => 'Lituânia', 'nationality' => 'Lituana', 'ddi' => '370'],
            ['id' => '442', 'name' => 'Luxemburgo', 'nationality' => 'Luxemburguesa', 'ddi' => '352'],
            ['id' => '446', 'name' => 'Macau', 'nationality' => 'Macaense', 'ddi' => '853'],
            ['id' => '450', 'name' => 'Madagáscar', 'nationality' => 'Malgaxe', 'ddi' => ''],
            ['id' => '454', 'name' => 'Malawi', 'nationality' => 'Malauiana', 'ddi' => '265'],
            ['id' => '458', 'name' => 'Malásia', 'nationality' => 'Malaia', 'ddi' => '60'],
            ['id' => '462', 'name' => 'Maldivas', 'nationality' => 'Maldívia', 'ddi' => '960'],
            ['id' => '466', 'name' => 'Mali', 'nationality' => 'Maliana', 'ddi' => '223'],
            ['id' => '470', 'name' => 'Malta', 'nationality' => 'Maltesa', 'ddi' => ''],
            ['id' => '474', 'name' => 'Martinica', 'nationality' => 'Martinicana', 'ddi' => '596'],
            ['id' => '478', 'name' => 'Mauritânia', 'nationality' => 'Mauritana', 'ddi' => '222'],
            ['id' => '480', 'name' => 'Maurícia', 'nationality' => 'Mauriciana', 'ddi' => '230'],
            ['id' => '484', 'name' => 'México', 'nationality' => 'Mexicana', 'ddi' => '52'],
            ['id' => '492', 'name' => 'Mônaco', 'nationality' => 'Monegasca', 'ddi' => '377'],
            ['id' => '496', 'name' => 'Mongólia', 'nationality' => 'Mongol', 'ddi' => '976'],
            ['id' => '498', 'name' => 'Moldávia', 'nationality' => 'Moldávia', 'ddi' => ''],
            ['id' => '499', 'name' => 'Montenegro', 'nationality' => 'Montenegrina', 'ddi' => '382'],
            ['id' => '500', 'name' => 'Montserrat', 'nationality' => 'Monserratense', 'ddi' => ''],
            ['id' => '504', 'name' => 'Marrocos', 'nationality' => 'Marroquina', 'ddi' => '212'],
            ['id' => '508', 'name' => 'Moçambique', 'nationality' => 'Moçambicana', 'ddi' => '258'],
            ['id' => '512', 'name' => 'Omã', 'nationality' => 'Omanense', 'ddi' => ''],
            ['id' => '516', 'name' => 'Namíbia', 'nationality' => 'Namibiana', 'ddi' => '264'],
            ['id' => '520', 'name' => 'Nauru', 'nationality' => 'Nauruense', 'ddi' => '674'],
            ['id' => '524', 'name' => 'Nepal', 'nationality' => 'Nepalesa', 'ddi' => '977'],
            ['id' => '528', 'name' => 'Holanda', 'nationality' => 'Holandesa', 'ddi' => '31'],
            ['id' => '530', 'name' => 'Antilhas Holandesas', 'nationality' => 'Antilhana', 'ddi' => '599'],
            ['id' => '531', 'name' => 'Curaçao', 'nationality' => 'Curacaunse', 'ddi' => ''],
            ['id' => '533', 'name' => 'Aruba', 'nationality' => 'Arubana', 'ddi' => '297'],
            ['id' => '534', 'name' => 'Sint Maarten (Parte Holandesa] ', 'nationality' => '', 'ddi' => ''],
            ['id' => '535', 'name' => 'Bonaire, Saint Eustatius E Saba', 'nationality' => 'Bonaire', 'ddi' => ''],
            ['id' => '540', 'name' => 'Nova Caledónia', 'nationality' => 'Neocaledônia', 'ddi' => '687'],
            ['id' => '548', 'name' => 'Vanuatu', 'nationality' => 'Vanuatense', 'ddi' => '678'],
            ['id' => '554', 'name' => 'Nova Zelândia', 'nationality' => 'Neozelandesa', 'ddi' => '64'],
            ['id' => '558', 'name' => 'Nicarágua', 'nationality' => 'Nicaraguense', 'ddi' => '505'],
            ['id' => '562', 'name' => 'Níger', 'nationality' => 'Nigerina', 'ddi' => ''],
            ['id' => '566', 'name' => 'Nigéria', 'nationality' => 'Nigeriana', 'ddi' => '234'],
            ['id' => '570', 'name' => 'Niue', 'nationality' => 'Niuense', 'ddi' => '683'],
            ['id' => '574', 'name' => 'Ilha Norfolk', 'nationality' => 'Norfolquiana', 'ddi' => '672'],
            ['id' => '578', 'name' => 'Noruega', 'nationality' => 'Norueguesa', 'ddi' => '47'],
            ['id' => '580', 'name' => 'Ilhas Marianas do Norte', 'nationality' => '', 'ddi' => ''],
            ['id' => '581', 'name' => 'Ilhas Menores Distantes dos Estados Unidos', 'nationality' => '', 'ddi' => ''],
            ['id' => '583', 'name' => 'Estados Federados da Micronésia', 'nationality' => 'Micronésia', 'ddi' => '691'],
            ['id' => '584', 'name' => 'Ilhas Marshall', 'nationality' => 'Marshallina', 'ddi' => '692'],
            ['id' => '585', 'name' => 'Palau', 'nationality' => 'Palauense', 'ddi' => '680'],
            ['id' => '586', 'name' => 'Paquistão', 'nationality' => 'Paquistanesa', 'ddi' => '92'],
            ['id' => '591', 'name' => 'Panamá', 'nationality' => 'Panamense', 'ddi' => '507'],
            ['id' => '598', 'name' => 'Papua-Nova Guiné', 'nationality' => 'Papua', 'ddi' => ''],
            ['id' => '600', 'name' => 'Paraguai', 'nationality' => 'Paraguaia', 'ddi' => '595'],
            ['id' => '604', 'name' => 'Peru', 'nationality' => 'Peruana', 'ddi' => '51'],
            ['id' => '608', 'name' => 'Filipinas', 'nationality' => 'Filipina', 'ddi' => '63'],
            ['id' => '612', 'name' => 'Ilhas Pitcairn', 'nationality' => '', 'ddi' => ''],
            ['id' => '616', 'name' => 'Polônia', 'nationality' => 'Polonesa', 'ddi' => '48'],
            ['id' => '620', 'name' => 'Portugal', 'nationality' => 'Portuguesa', 'ddi' => '351'],
            ['id' => '624', 'name' => 'Guiné-Bissau', 'nationality' => 'Guineense', 'ddi' => ''],
            ['id' => '626', 'name' => 'Timor-Leste', 'nationality' => 'Timorense', 'ddi' => ''],
            ['id' => '630', 'name' => 'Porto Rico', 'nationality' => 'Porto-riquenha', 'ddi' => ''],
            ['id' => '634', 'name' => 'Catar', 'nationality' => 'Catariana', 'ddi' => '974'],
            ['id' => '638', 'name' => 'Réunion', 'nationality' => '', 'ddi' => ''],
            ['id' => '642', 'name' => 'Roménia', 'nationality' => 'Romena', 'ddi' => ''],
            ['id' => '643', 'name' => 'Rússia', 'nationality' => 'Russa', 'ddi' => '7'],
            ['id' => '646', 'name' => 'Ruanda', 'nationality' => 'Ruandesa', 'ddi' => '250'],
            ['id' => '652', 'name' => 'São Bartolomeu', 'nationality' => 'São-Bartolomense', 'ddi' => ''],
            ['id' => '654', 'name' => 'Santa Helena', 'nationality' => 'Santa-helenense', 'ddi' => '290'],
            ['id' => '659', 'name' => 'São Cristóvão e Nevis', 'nationality' => '', 'ddi' => ''],
            ['id' => '660', 'name' => 'Anguilla', 'nationality' => 'Anguilana', 'ddi' => ''],
            ['id' => '662', 'name' => 'Santa Lúcia', 'nationality' => 'Santa-lucense', 'ddi' => ''],
            ['id' => '663', 'name' => 'Saint-Martin (Parte Francesa]', 'nationality' => 'São-Martinhense', 'ddi' => ''],
            ['id' => '666', 'name' => 'São Pedro e Miquelão', 'nationality' => '', 'ddi' => ''],
            ['id' => '670', 'name' => 'São Vicente e Granadinas', 'nationality' => '', 'ddi' => ''],
            ['id' => '674', 'name' => 'San Marino', 'nationality' => 'São-marinhense', 'ddi' => '378'],
            ['id' => '678', 'name' => 'São Tomé e Príncipe', 'nationality' => 'Santomense', 'ddi' => '239'],
            ['id' => '680', 'name' => 'Sark', 'nationality' => '', 'ddi' => ''],
            ['id' => '682', 'name' => 'Arábia Saudita', 'nationality' => 'Saudita', 'ddi' => '966'],
            ['id' => '686', 'name' => 'Senegal', 'nationality' => 'Senegalesa', 'ddi' => '221'],
            ['id' => '688', 'name' => 'Sérvia', 'nationality' => 'Sérvia', 'ddi' => '381'],
            ['id' => '690', 'name' => 'Seicheles', 'nationality' => '', 'ddi' => ''],
            ['id' => '694', 'name' => 'Serra Leoa', 'nationality' => 'Serra-leonesa', 'ddi' => '232'],
            ['id' => '702', 'name' => 'Cingapura', 'nationality' => 'Cingapurense', 'ddi' => ''],
            ['id' => '703', 'name' => 'Eslováquia', 'nationality' => 'Eslovaca', 'ddi' => '421'],
            ['id' => '704', 'name' => 'Vietnã', 'nationality' => 'Vietnamita', 'ddi' => ''],
            ['id' => '705', 'name' => 'Eslovênia', 'nationality' => 'Eslovena', 'ddi' => '386'],
            ['id' => '706', 'name' => 'Somália', 'nationality' => 'Somali', 'ddi' => ''],
            ['id' => '710', 'name' => 'África do Sul', 'nationality' => 'Sul-africana', 'ddi' => '27'],
            ['id' => '716', 'name' => 'Zimbábue', 'nationality' => 'Zimbabuana', 'ddi' => ''],
            ['id' => '724', 'name' => 'Espanha', 'nationality' => 'Espanhola', 'ddi' => '34'],
            ['id' => '728', 'name' => 'Sudão Do Sul', 'nationality' => '', 'ddi' => ''],
            ['id' => '729', 'name' => 'Sudão', 'nationality' => 'Sudanesa', 'ddi' => ''],
            ['id' => '732', 'name' => 'Saara Ocidental', 'nationality' => 'Saráui', 'ddi' => '212'],
            ['id' => '740', 'name' => 'Suriname', 'nationality' => 'Surinamense', 'ddi' => '597'],
            ['id' => '744', 'name' => 'Svalbard and Jan Mayen', 'nationality' => '', 'ddi' => ''],
            ['id' => '748', 'name' => 'Suazilândia', 'nationality' => 'Suazilandesa', 'ddi' => '268'],
            ['id' => '752', 'name' => 'Suécia', 'nationality' => 'Sueca', 'ddi' => '46'],
            ['id' => '756', 'name' => 'Suíça', 'nationality' => 'Suíça', 'ddi' => '41'],
            ['id' => '760', 'name' => 'Síria', 'nationality' => 'Síria', 'ddi' => '963'],
            ['id' => '762', 'name' => 'Tajiquistão', 'nationality' => 'Tajique', 'ddi' => ''],
            ['id' => '764', 'name' => 'Tailândia', 'nationality' => 'Tailandesa', 'ddi' => '66'],
            ['id' => '768', 'name' => 'Togo', 'nationality' => 'Togolesa', 'ddi' => '228'],
            ['id' => '772', 'name' => 'Tokelau', 'nationality' => '', 'ddi' => ''],
            ['id' => '776', 'name' => 'Tonga', 'nationality' => 'Tonganesa', 'ddi' => '676'],
            ['id' => '780', 'name' => 'Trinidad e Tobago', 'nationality' => 'Trinitina', 'ddi' => ''],
            ['id' => '784', 'name' => 'Emirados Árabes Unidos', 'nationality' => 'Emiriana', 'ddi' => '971'],
            ['id' => '788', 'name' => 'Tunísia', 'nationality' => 'Tunisiana', 'ddi' => '216'],
            ['id' => '792', 'name' => 'Turquia', 'nationality' => 'Turca', 'ddi' => '90'],
            ['id' => '795', 'name' => 'Turcomenistão', 'nationality' => 'Turcomena', 'ddi' => '993'],
            ['id' => '796', 'name' => 'Turks e Caicos', 'nationality' => 'Turco-caicense', 'ddi' => ''],
            ['id' => '798', 'name' => 'Tuvalu', 'nationality' => 'Tuvaluana', 'ddi' => '688'],
            ['id' => '800', 'name' => 'Uganda', 'nationality' => 'Ugandesa', 'ddi' => '256'],
            ['id' => '804', 'name' => 'Ucrânia', 'nationality' => 'Ucraniana', 'ddi' => '380'],
            ['id' => '807', 'name' => 'Macedônia', 'nationality' => 'Macedônica', 'ddi' => ''],
            ['id' => '818', 'name' => 'Egito', 'nationality' => 'Egipcia', 'ddi' => ''],
            ['id' => '826', 'name' => 'Reino Unido', 'nationality' => 'Britância', 'ddi' => ''],
            ['id' => '830', 'name' => 'Ilhas Do Canal', 'nationality' => '', 'ddi' => ''],
            ['id' => '831', 'name' => 'Guernsey', 'nationality' => 'Guernesiana', 'ddi' => '44'],
            ['id' => '832', 'name' => 'Jersey', 'nationality' => 'Jersiana', 'ddi' => '44'],
            ['id' => '833', 'name' => 'Ilha de Man', 'nationality' => 'Manesa', 'ddi' => '44'],
            ['id' => '834', 'name' => 'Tanzânia', 'nationality' => 'Tanzaniana', 'ddi' => '255'],
            ['id' => '840', 'name' => 'Estados Unidos', 'nationality' => 'Norte-Americana', 'ddi' => ''],
            ['id' => '850', 'name' => 'Ilhas Virgens Americanas', 'nationality' => '', 'ddi' => ''],
            ['id' => '854', 'name' => 'Burkina Faso', 'nationality' => 'Burquinense', 'ddi' => '226'],
            ['id' => '858', 'name' => 'Uruguai', 'nationality' => 'Uruguaia', 'ddi' => '598'],
            ['id' => '860', 'name' => 'Uzbequistão', 'nationality' => 'Uzbeque', 'ddi' => '998'],
            ['id' => '862', 'name' => 'Venezuela', 'nationality' => 'Venezuelana', 'ddi' => '58'],
            ['id' => '876', 'name' => 'Wallis e Futuna', 'nationality' => 'Wallis-futunense', 'ddi' => '681'],
            ['id' => '882', 'name' => 'Samoa', 'nationality' => 'Samoana', 'ddi' => ''],
            ['id' => '887', 'name' => 'Iémen', 'nationality' => 'Iemenita', 'ddi' => ''],
            ['id' => '894', 'name' => 'Zâmbia', 'nationality' => 'Zambiana', 'ddi' => '260'],
            ['id' => '999', 'name' => 'Outra nationality', 'nationality' => '', 'ddi' => '']
        ]);
    }
}
