<?php

namespace Database\Seeders\Helpers;

use Illuminate\Database\Seeder;
use App\Models\Helpers\CursoSuperior;

class CursoSuperiorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CursoSuperior::insert([
            ['id' => '0111C012', 'nome' => 'Ciência da educação - Bacharelado'],
            ['id' => '0111C014', 'nome' => 'Ciência da educação - Sequencial'],
            ['id' => '0111P013', 'nome' => 'Processos escolares - Tecnológico'],
            ['id' => '0111P022', 'nome' => 'Psicopedagogia - Bacharelado'],
            ['id' => '0111P024', 'nome' => 'Psicopedagogia - Sequencial'],
            ['id' => '0112E011', 'nome' => 'Educação infantil formação de professor - Licenciatura'],
            ['id' => '0113E011', 'nome' => 'Educação do campo formação de professor - Licenciatura'],
            ['id' => '0113E021', 'nome' => 'Educação especial formação de professor - Licenciatura'],
            ['id' => '0113E031', 'nome' => 'Educação indígena formação de professor - Licenciatura'],
            ['id' => '0113F011', 'nome' => 'Formação pedagógica de professor para a educação básica - Licenciatura'],
            ['id' => '0113F014', 'nome' => 'Formação pedagógica de professor para a educação básica - Sequencial'],
            ['id' => '0113P011', 'nome' => 'Pedagogia - Licenciatura'],
            ['id' => '0113P012', 'nome' => 'Pedagogia - Bacharelado'],
            ['id' => '0113P014', 'nome' => 'Pedagogia - Sequencial'],
            ['id' => '0114A011', 'nome' => 'Artes formação de professor - Licenciatura'],
            ['id' => '0114A014', 'nome' => 'Artes formação de professor - Sequencial'],
            ['id' => '0114A021', 'nome' => 'Artes visuais formação de professor - Licenciatura'],
            ['id' => '0114B011', 'nome' => 'Biologia formação de professor - Licenciatura'],
            ['id' => '0114C011', 'nome' => 'Ciências agrárias formação de professor - Licenciatura'],
            ['id' => '0114C021', 'nome' => 'Ciências naturais formação de professor - Licenciatura'],
            ['id' => '0114C031', 'nome' => 'Ciências sociais formação de professor - Licenciatura'],
            ['id' => '0114C041', 'nome' => 'Cinema e audiovisual formação de professor - Licenciatura'],
            ['id' => '0114C051', 'nome' => 'Computação formação de professor - Licenciatura'],
            ['id' => '0114D011', 'nome' => 'Dança formação de professor - Licenciatura'],
            ['id' => '0114E011', 'nome' => 'Economia doméstica formação de professor - Licenciatura'],
            ['id' => '0114E021', 'nome' => 'Educação do campo em áreas de conhecimento da educação básica formação de professor - Licenciatura'],
            ['id' => '0114E031', 'nome' => 'Educação física formação de professor - Licenciatura'],
            ['id' => '0114E041', 'nome' => 'Educação indígena em áreas de conhecimento da educação básica formação de professor - Licenciatura'],
            ['id' => '0114E051', 'nome' => 'Enfermagem formação de professor - Licenciatura'],
            ['id' => '0114E061', 'nome' => 'Ensino profissionalizante em área específica formação de professor - Licenciatura'],
            ['id' => '0114E071', 'nome' => 'Ensino religioso formação de professor - Licenciatura'],
            ['id' => '0114E081', 'nome' => 'Estatística formação de professor - Licenciatura'],
            ['id' => '0114F011', 'nome' => 'Filosofia formação de professor - Licenciatura'],
            ['id' => '0114F021', 'nome' => 'Física formação de professor - Licenciatura'],
            ['id' => '0114G011', 'nome' => 'Geografia formação de professor - Licenciatura'],
            ['id' => '0114H011', 'nome' => 'História formação de professor - Licenciatura'],
            ['id' => '0114M011', 'nome' => 'Matemática formação de professor - Licenciatura'],
            ['id' => '0114M021', 'nome' => 'Música formação de professor - Licenciatura'],
            ['id' => '0114P011', 'nome' => 'Psicologia formação de professor - Licenciatura'],
            ['id' => '0114Q011', 'nome' => 'Química formação de professor - Licenciatura'],
            ['id' => '0114T011', 'nome' => 'Teatro formação de professor - Licenciatura'],
            ['id' => '0115L011', 'nome' => 'Letras alemão formação de professor - Licenciatura'],
            ['id' => '0115L021', 'nome' => 'Letras espanhol formação de professor - Licenciatura'],
            ['id' => '0115L031', 'nome' => 'Letras francês formação de professor - Licenciatura'],
            ['id' => '0115L041', 'nome' => 'Letras inglês formação de professor - Licenciatura'],
            ['id' => '0115L051', 'nome' => 'Letras italiano formação de professor - Licenciatura'],
            ['id' => '0115L061', 'nome' => 'Letras japonês formação de professor - Licenciatura'],
            ['id' => '0115L071', 'nome' => 'Letras língua brasileira de sinais formação de professor - Licenciatura'],
            ['id' => '0115L081', 'nome' => 'Letras línguas estrangeiras clássicas formação de professor - Licenciatura'],
            ['id' => '0115L091', 'nome' => 'Letras linguística formação de professor - Licenciatura'],
            ['id' => '0115L101', 'nome' => 'Letras outras línguas estrangeiras modernas formação de professor - Licenciatura'],
            ['id' => '0115L111', 'nome' => 'Letras português alemão formação de professor - Licenciatura'],
            ['id' => '0115L121', 'nome' => 'Letras português espanhol formação de professor - Licenciatura'],
            ['id' => '0115L131', 'nome' => 'Letras português formação de professor - Licenciatura'],
            ['id' => '0115L141', 'nome' => 'Letras português francês formação de professor - Licenciatura'],
            ['id' => '0115L151', 'nome' => 'Letras português inglês formação de professor - Licenciatura'],
            ['id' => '0115L161', 'nome' => 'Letras português italiano formação de professor - Licenciatura'],
            ['id' => '0115L171', 'nome' => 'Letras português japonês formação de professor - Licenciatura'],
            ['id' => '0115L181', 'nome' => 'Letras português língua brasileira de sinais formação de professor - Licenciatura'],
            ['id' => '0115L191', 'nome' => 'Letras português línguas estrangeiras clássicas formação de professor - Licenciatura'],
            ['id' => '0115L201', 'nome' => 'Letras português outras línguas estrangeiras modernas formação de professor - Licenciatura'],
            ['id' => '0115L211', 'nome' => 'Letras tradutor e intérprete formação de professor - Licenciatura'],
            ['id' => '0188P011', 'nome' => 'Programas interdisciplinares abrangendo educação - Licenciatura'],
            ['id' => '0188P012', 'nome' => 'Programas interdisciplinares abrangendo educação - Bacharelado'],
            ['id' => '0188P013', 'nome' => 'Programas interdisciplinares abrangendo educação - Tecnológico'],
            ['id' => '0211A012', 'nome' => 'Animação - Bacharelado'],
            ['id' => '0211A013', 'nome' => 'Animação - Tecnológico'],
            ['id' => '0211A014', 'nome' => 'Animação - Sequencial'],
            ['id' => '0211C012', 'nome' => 'Cinema e audiovisual - Bacharelado'],
            ['id' => '0211C013', 'nome' => 'Cinema e audiovisual - Tecnológico'],
            ['id' => '0211C014', 'nome' => 'Cinema e audiovisual - Sequencial'],
            ['id' => '0211C023', 'nome' => 'Comunicação assistiva - Tecnológico'],
            ['id' => '0211D012', 'nome' => 'Design gráfico - Bacharelado'],
            ['id' => '0211D013', 'nome' => 'Design gráfico - Tecnológico'],
            ['id' => '0211D014', 'nome' => 'Design gráfico - Sequencial'],
            ['id' => '0211F012', 'nome' => 'Fotografia - Bacharelado'],
            ['id' => '0211F013', 'nome' => 'Fotografia - Tecnológico'],
            ['id' => '0211F014', 'nome' => 'Fotografia - Sequencial'],
            ['id' => '0211P012', 'nome' => 'Produção audiovisual - Bacharelado'],
            ['id' => '0211P013', 'nome' => 'Produção audiovisual - Tecnológico'],
            ['id' => '0211P014', 'nome' => 'Produção audiovisual - Sequencial'],
            ['id' => '0211P023', 'nome' => 'Produção cênica - Tecnológico'],
            ['id' => '0211P032', 'nome' => 'Produção cultural - Bacharelado'],
            ['id' => '0211P033', 'nome' => 'Produção cultural - Tecnológico'],
            ['id' => '0211P034', 'nome' => 'Produção cultural - Sequencial'],
            ['id' => '0211P043', 'nome' => 'Produção fonográfica - Tecnológico'],
            ['id' => '0211P052', 'nome' => 'Produção multimídia - Bacharelado'],
            ['id' => '0211P053', 'nome' => 'Produção multimídia - Tecnológico'],
            ['id' => '0211P054', 'nome' => 'Produção multimídia - Sequencial'],
            ['id' => '0212D012', 'nome' => 'Desenho industrial - Bacharelado'],
            ['id' => '0212D022', 'nome' => 'Design - Bacharelado'],
            ['id' => '0212D023', 'nome' => 'Design - Tecnológico'],
            ['id' => '0212D032', 'nome' => 'Design de interiores - Bacharelado'],
            ['id' => '0212D033', 'nome' => 'Design de interiores - Tecnológico'],
            ['id' => '0212D034', 'nome' => 'Design de interiores - Sequencial'],
            ['id' => '0212D042', 'nome' => 'Design de produto - Bacharelado'],
            ['id' => '0212D043', 'nome' => 'Design de produto - Tecnológico'],
            ['id' => '0212D044', 'nome' => 'Design de produto - Sequencial'],
            ['id' => '0212M012', 'nome' => 'Moda - Bacharelado'],
            ['id' => '0212M013', 'nome' => 'Moda - Tecnológico'],
            ['id' => '0212M014', 'nome' => 'Moda - Sequencial'],
            ['id' => '0213A012', 'nome' => 'Artes - Bacharelado'],
            ['id' => '0213A013', 'nome' => 'Artes - Tecnológico'],
            ['id' => '0213A014', 'nome' => 'Artes - Sequencial'],
            ['id' => '0213A022', 'nome' => 'Artes plásticas - Bacharelado'],
            ['id' => '0213A023', 'nome' => 'Artes plásticas - Tecnológico'],
            ['id' => '0213A024', 'nome' => 'Artes plásticas - Sequencial'],
            ['id' => '0213A032', 'nome' => 'Artes visuais - Bacharelado'],
            ['id' => '0213A033', 'nome' => 'Artes visuais - Tecnológico'],
            ['id' => '0213H012', 'nome' => 'História da arte - Bacharelado'],
            ['id' => '0214F013', 'nome' => 'Fabricação de instrumentos musicais não industrial - Tecnológico'],
            ['id' => '0215A012', 'nome' => 'Artes cênicas - Bacharelado'],
            ['id' => '0215A013', 'nome' => 'Artes cênicas - Tecnológico'],
            ['id' => '0215D012', 'nome' => 'Dança - Bacharelado'],
            ['id' => '0215D013', 'nome' => 'Dança - Tecnológico'],
            ['id' => '0215M012', 'nome' => 'Música - Bacharelado'],
            ['id' => '0215M013', 'nome' => 'Música - Tecnológico'],
            ['id' => '0215M014', 'nome' => 'Música - Sequencial'],
            ['id' => '0215T012', 'nome' => 'Teatro - Bacharelado'],
            ['id' => '0215T013', 'nome' => 'Teatro - Tecnológico'],
            ['id' => '0221C012', 'nome' => 'Ciências da religião - Bacharelado'],
            ['id' => '0221T012', 'nome' => 'Teologia - Bacharelado'],
            ['id' => '0221T014', 'nome' => 'Teologia - Sequencial'],
            ['id' => '0222A012', 'nome' => 'Arqueologia - Bacharelado'],
            ['id' => '0222A013', 'nome' => 'Arqueologia - Tecnológico'],
            ['id' => '0222C012', 'nome' => 'Conservação e restauro - Bacharelado'],
            ['id' => '0222C013', 'nome' => 'Conservação e restauro - Tecnológico'],
            ['id' => '0222H012', 'nome' => 'História - Bacharelado'],
            ['id' => '0222H014', 'nome' => 'História - Sequencial'],
            ['id' => '0223F012', 'nome' => 'Filosofia - Bacharelado'],
            ['id' => '0223F014', 'nome' => 'Filosofia - Sequencial'],
            ['id' => '0231L012', 'nome' => 'Letras alemão - Bacharelado'],
            ['id' => '0231L023', 'nome' => 'Letras escrita criativa - Tecnológico'],
            ['id' => '0231L024', 'nome' => 'Letras escrita criativa - Sequencial'],
            ['id' => '0231L032', 'nome' => 'Letras espanhol - Bacharelado'],
            ['id' => '0231L034', 'nome' => 'Letras espanhol - Sequencial'],
            ['id' => '0231L042', 'nome' => 'Letras francês - Bacharelado'],
            ['id' => '0231L052', 'nome' => 'Letras inglês - Bacharelado'],
            ['id' => '0231L054', 'nome' => 'Letras inglês - Sequencial'],
            ['id' => '0231L062', 'nome' => 'Letras italiano - Bacharelado'],
            ['id' => '0231L072', 'nome' => 'Letras japonês - Bacharelado'],
            ['id' => '0231L082', 'nome' => 'Letras língua brasileira de sinais - Bacharelado'],
            ['id' => '0231L083', 'nome' => 'Letras língua brasileira de sinais - Tecnológico'],
            ['id' => '0231L084', 'nome' => 'Letras língua brasileira de sinais - Sequencial'],
            ['id' => '0231L092', 'nome' => 'Letras línguas estrangeiras clássicas - Bacharelado'],
            ['id' => '0231L094', 'nome' => 'Letras línguas estrangeiras clássicas - Sequencial'],
            ['id' => '0231L102', 'nome' => 'Letras linguística - Bacharelado'],
            ['id' => '0231L112', 'nome' => 'Letras outras línguas estrangeiras modernas - Bacharelado'],
            ['id' => '0231L122', 'nome' => 'Letras português - Bacharelado'],
            ['id' => '0231L124', 'nome' => 'Letras português - Sequencial'],
            ['id' => '0231L132', 'nome' => 'Letras português alemão - Bacharelado'],
            ['id' => '0231L142', 'nome' => 'Letras português espanhol - Bacharelado'],
            ['id' => '0231L152', 'nome' => 'Letras português francês - Bacharelado'],
            ['id' => '0231L162', 'nome' => 'Letras português inglês - Bacharelado'],
            ['id' => '0231L172', 'nome' => 'Letras português italiano - Bacharelado'],
            ['id' => '0231L182', 'nome' => 'Letras português japonês - Bacharelado'],
            ['id' => '0231L192', 'nome' => 'Letras português língua brasileira de sinais - Bacharelado'],
            ['id' => '0231L202', 'nome' => 'Letras português línguas estrangeiras clássicas - Bacharelado'],
            ['id' => '0231L212', 'nome' => 'Letras português outras línguas estrangeiras modernas - Bacharelado'],
            ['id' => '0231L222', 'nome' => 'Letras tradutor e intérprete - Bacharelado'],
            ['id' => '0231L223', 'nome' => 'Letras tradutor e intérprete - Tecnológico'],
            ['id' => '0231L224', 'nome' => 'Letras tradutor e intérprete - Sequencial'],
            ['id' => '0288P012', 'nome' => 'Programas interdisciplinares abrangendo artes e humanidades - Bacharelado'],
            ['id' => '0288P014', 'nome' => 'Programas interdisciplinares abrangendo artes e humanidades - Sequencial'],
            ['id' => '0311E012', 'nome' => 'Economia - Bacharelado'],
            ['id' => '0311E014', 'nome' => 'Economia - Sequencial'],
            ['id' => '0312A012', 'nome' => 'Antropologia - Bacharelado'],
            ['id' => '0312A014', 'nome' => 'Antropologia - Sequencial'],
            ['id' => '0312C012', 'nome' => 'Ciência política - Bacharelado'],
            ['id' => '0312C014', 'nome' => 'Ciência política - Sequencial'],
            ['id' => '0312C022', 'nome' => 'Ciências sociais - Bacharelado'],
            ['id' => '0312C024', 'nome' => 'Ciências sociais - Sequencial'],
            ['id' => '0312G012', 'nome' => 'Geografia - Bacharelado'],
            ['id' => '0312R012', 'nome' => 'Relações internacionais - Bacharelado'],
            ['id' => '0312R014', 'nome' => 'Relações internacionais - Sequencial'],
            ['id' => '0312S012', 'nome' => 'Sociologia - Bacharelado'],
            ['id' => '0312S014', 'nome' => 'Sociologia - Sequencial'],
            ['id' => '0313P012', 'nome' => 'Psicologia - Bacharelado'],
            ['id' => '0313P014', 'nome' => 'Psicologia - Sequencial'],
            ['id' => '0321C012', 'nome' => 'Comunicação social - Bacharelado'],
            ['id' => '0321J012', 'nome' => 'Jornalismo - Bacharelado'],
            ['id' => '0321J014', 'nome' => 'Jornalismo - Sequencial'],
            ['id' => '0321P012', 'nome' => 'Produção editorial - Bacharelado'],
            ['id' => '0321P013', 'nome' => 'Produção editorial - Tecnológico'],
            ['id' => '0321P014', 'nome' => 'Produção editorial - Sequencial'],
            ['id' => '0321R012', 'nome' => 'Rádio, TV e internet - Bacharelado'],
            ['id' => '0321R013', 'nome' => 'Rádio, TV e internet - Tecnológico'],
            ['id' => '0321R014', 'nome' => 'Rádio, TV e internet - Sequencial'],
            ['id' => '0322A012', 'nome' => 'Arquivologia - Bacharelado'],
            ['id' => '0322B012', 'nome' => 'Biblioteconomia - Bacharelado'],
            ['id' => '0322G012', 'nome' => 'Gestão da informação - Bacharelado'],
            ['id' => '0322G014', 'nome' => 'Gestão da informação - Sequencial'],
            ['id' => '0322M012', 'nome' => 'Museologia - Bacharelado'],
            ['id' => '0322M013', 'nome' => 'Museologia - Tecnológico'],
            ['id' => '0322M014', 'nome' => 'Museologia - Sequencial'],
            ['id' => '0388P012', 'nome' => 'Programas interdisciplinares abrangendo ciências sociais, jornalismo e informação - Bacharelado'],
            ['id' => '0388P014', 'nome' => 'Programas interdisciplinares abrangendo ciências sociais, jornalismo e informação - Sequencial'],
            ['id' => '0411C012', 'nome' => 'Contabilidade - Bacharelado'],
            ['id' => '0411C013', 'nome' => 'Contabilidade - Tecnológico'],
            ['id' => '0411C014', 'nome' => 'Contabilidade - Sequencial'],
            ['id' => '0411G013', 'nome' => 'Gestão fiscal e tributária - Tecnológico'],
            ['id' => '0412G012', 'nome' => 'Gestão financeira - Bacharelado'],
            ['id' => '0412G013', 'nome' => 'Gestão financeira - Tecnológico'],
            ['id' => '0412G014', 'nome' => 'Gestão financeira - Sequencial'],
            ['id' => '0412S013', 'nome' => 'Seguros - Tecnológico'],
            ['id' => '0412S014', 'nome' => 'Seguros - Sequencial'],
            ['id' => '0413A012', 'nome' => 'Administração - Bacharelado'],
            ['id' => '0413A014', 'nome' => 'Administração - Sequencial'],
            ['id' => '0413A022', 'nome' => 'Administração pública - Bacharelado'],
            ['id' => '0413A023', 'nome' => 'Administração pública - Tecnológico'],
            ['id' => '0413A024', 'nome' => 'Administração pública - Sequencial'],
            ['id' => '0413C012', 'nome' => 'Comércio exterior - Bacharelado'],
            ['id' => '0413C013', 'nome' => 'Comércio exterior - Tecnológico'],
            ['id' => '0413C014', 'nome' => 'Comércio exterior - Sequencial'],
            ['id' => '0413E012', 'nome' => 'Empreendedorismo - Bacharelado'],
            ['id' => '0413E013', 'nome' => 'Empreendedorismo - Tecnológico'],
            ['id' => '0413E014', 'nome' => 'Empreendedorismo - Sequencial'],
            ['id' => '0413G013', 'nome' => 'Gestão da produção - Tecnológico'],
            ['id' => '0413G014', 'nome' => 'Gestão da produção - Sequencial'],
            ['id' => '0413G023', 'nome' => 'Gestão da qualidade - Tecnológico'],
            ['id' => '0413G024', 'nome' => 'Gestão da qualidade - Sequencial'],
            ['id' => '0413G032', 'nome' => 'Gestão da saúde - Bacharelado'],
            ['id' => '0413G033', 'nome' => 'Gestão da saúde - Tecnológico'],
            ['id' => '0413G034', 'nome' => 'Gestão da saúde - Sequencial'],
            ['id' => '0413G042', 'nome' => 'Gestão de cooperativas - Bacharelado'],
            ['id' => '0413G043', 'nome' => 'Gestão de cooperativas - Tecnológico'],
            ['id' => '0413G044', 'nome' => 'Gestão de cooperativas - Sequencial'],
            ['id' => '0413G052', 'nome' => 'Gestão de negócios - Bacharelado'],
            ['id' => '0413G053', 'nome' => 'Gestão de negócios - Tecnológico'],
            ['id' => '0413G054', 'nome' => 'Gestão de negócios - Sequencial'],
            ['id' => '0413G062', 'nome' => 'Gestão de negócios internacionais - Bacharelado'],
            ['id' => '0413G064', 'nome' => 'Gestão de negócios internacionais - Sequencial'],
            ['id' => '0413G073', 'nome' => 'Gestão de pessoas - Tecnológico'],
            ['id' => '0413G074', 'nome' => 'Gestão de pessoas - Sequencial'],
            ['id' => '0413G083', 'nome' => 'Gestão de serviços - Tecnológico'],
            ['id' => '0413G084', 'nome' => 'Gestão de serviços - Sequencial'],
            ['id' => '0413G092', 'nome' => 'Gestão do agronegócio - Bacharelado'],
            ['id' => '0413G093', 'nome' => 'Gestão do agronegócio - Tecnológico'],
            ['id' => '0413G094', 'nome' => 'Gestão do agronegócio - Sequencial'],
            ['id' => '0413G103', 'nome' => 'Gestão estratégica - Tecnológico'],
            ['id' => '0413G104', 'nome' => 'Gestão estratégica - Sequencial'],
            ['id' => '0413G113', 'nome' => 'Gestão hospitalar - Tecnológico'],
            ['id' => '0413G114', 'nome' => 'Gestão hospitalar - Sequencial'],
            ['id' => '0413G122', 'nome' => 'Gestão pública - Bacharelado'],
            ['id' => '0413G123', 'nome' => 'Gestão pública - Tecnológico'],
            ['id' => '0413G124', 'nome' => 'Gestão pública - Sequencial'],
            ['id' => '0413L012', 'nome' => 'Logística - Bacharelado'],
            ['id' => '0413L013', 'nome' => 'Logística - Tecnológico'],
            ['id' => '0413L014', 'nome' => 'Logística - Sequencial'],
            ['id' => '0414M012', 'nome' => 'Marketing - Bacharelado'],
            ['id' => '0414M013', 'nome' => 'Marketing - Tecnológico'],
            ['id' => '0414M014', 'nome' => 'Marketing - Sequencial'],
            ['id' => '0414P012', 'nome' => 'Publicidade e propaganda - Bacharelado'],
            ['id' => '0414P013', 'nome' => 'Publicidade e propaganda - Tecnológico'],
            ['id' => '0414P014', 'nome' => 'Publicidade e propaganda - Sequencial'],
            ['id' => '0414R012', 'nome' => 'Relações públicas - Bacharelado'],
            ['id' => '0414R013', 'nome' => 'Relações públicas - Tecnológico'],
            ['id' => '0414R014', 'nome' => 'Relações públicas - Sequencial'],
            ['id' => '0415S012', 'nome' => 'Secretariado - Bacharelado'],
            ['id' => '0415S013', 'nome' => 'Secretariado - Tecnológico'],
            ['id' => '0415S014', 'nome' => 'Secretariado - Sequencial'],
            ['id' => '0416G013', 'nome' => 'Gestão comercial - Tecnológico'],
            ['id' => '0416G014', 'nome' => 'Gestão comercial - Sequencial'],
            ['id' => '0416N012', 'nome' => 'Negócios imobiliários - Bacharelado'],
            ['id' => '0416N013', 'nome' => 'Negócios imobiliários - Tecnológico'],
            ['id' => '0416N014', 'nome' => 'Negócios imobiliários - Sequencial'],
            ['id' => '0421D012', 'nome' => 'Direito - Bacharelado'],
            ['id' => '0421D013', 'nome' => 'Direito - Tecnológico'],
            ['id' => '0421D014', 'nome' => 'Direito - Sequencial'],
            ['id' => '0421S013', 'nome' => 'Serviços jurídicos e cartoriais - Tecnológico'],
            ['id' => '0421S014', 'nome' => 'Serviços jurídicos e cartoriais - Sequencial'],
            ['id' => '0488P012', 'nome' => 'Programas interdisciplinares abrangendo negócios, administração e direito - Bacharelado'],
            ['id' => '0488P013', 'nome' => 'Programas interdisciplinares abrangendo negócios, administração e direito - Tecnológico'],
            ['id' => '0511B012', 'nome' => 'Biologia - Bacharelado'],
            ['id' => '0511B014', 'nome' => 'Biologia - Sequencial'],
            ['id' => '0512B012', 'nome' => 'Bioquímica - Bacharelado'],
            ['id' => '0512B022', 'nome' => 'Biotecnologia - Bacharelado'],
            ['id' => '0512B023', 'nome' => 'Biotecnologia - Tecnológico'],
            ['id' => '0512B024', 'nome' => 'Biotecnologia - Sequencial'],
            ['id' => '0512T013', 'nome' => 'Toxicologia - Tecnológico'],
            ['id' => '0521C012', 'nome' => 'Ciências ambientais - Bacharelado'],
            ['id' => '0521C014', 'nome' => 'Ciências ambientais - Sequencial'],
            ['id' => '0521E012', 'nome' => 'Ecologia - Bacharelado'],
            ['id' => '0531Q012', 'nome' => 'Química - Bacharelado'],
            ['id' => '0531Q013', 'nome' => 'Química - Tecnológico'],
            ['id' => '0531Q022', 'nome' => 'Química industrial e tecnológica - Bacharelado'],
            ['id' => '0531Q023', 'nome' => 'Química industrial e tecnológica - Tecnológico'],
            ['id' => '0531Q024', 'nome' => 'Química industrial e tecnológica - Sequencial'],
            ['id' => '0532G012', 'nome' => 'Geofísica - Bacharelado'],
            ['id' => '0532G022', 'nome' => 'Geologia - Bacharelado'],
            ['id' => '0532G033', 'nome' => 'Geoprocessamento - Tecnológico'],
            ['id' => '0532M012', 'nome' => 'Meteorologia - Bacharelado'],
            ['id' => '0532O012', 'nome' => 'Oceanografia - Bacharelado'],
            ['id' => '0533A012', 'nome' => 'Astronomia - Bacharelado'],
            ['id' => '0533F012', 'nome' => 'Física - Bacharelado'],
            ['id' => '0533F022', 'nome' => 'Física aplicada - Bacharelado'],
            ['id' => '0533F024', 'nome' => 'Física aplicada - Sequencial'],
            ['id' => '0533F032', 'nome' => 'Física médica - Bacharelado'],
            ['id' => '0541M012', 'nome' => 'Matemática - Bacharelado'],
            ['id' => '0541M014', 'nome' => 'Matemática - Sequencial'],
            ['id' => '0541M022', 'nome' => 'Matemática aplicada e computacional - Bacharelado'],
            ['id' => '0542C012', 'nome' => 'Ciências atuariais - Bacharelado'],
            ['id' => '0542E012', 'nome' => 'Estatística - Bacharelado'],
            ['id' => '0542E014', 'nome' => 'Estatística - Sequencial'],
            ['id' => '0588P012', 'nome' => 'Programas interdisciplinares abrangendo ciências naturais, matemática e estatística - Bacharelado'],
            ['id' => '0588P013', 'nome' => 'Programas interdisciplinares abrangendo ciências naturais, matemática e estatística - Tecnológico'],
            ['id' => '0588P014', 'nome' => 'Programas interdisciplinares abrangendo ciências naturais, matemática e estatística - Sequencial'],
            ['id' => '0612B013', 'nome' => 'Banco de dados - Tecnológico'],
            ['id' => '0612B014', 'nome' => 'Banco de dados - Sequencial'],
            ['id' => '0612D013', 'nome' => 'Defesa cibernética - Tecnológico'],
            ['id' => '0612G013', 'nome' => 'Gestão da tecnologia da informação - Tecnológico'],
            ['id' => '0612G014', 'nome' => 'Gestão da tecnologia da informação - Sequencial'],
            ['id' => '0612R012', 'nome' => 'Redes de computadores - Bacharelado'],
            ['id' => '0612R013', 'nome' => 'Redes de computadores - Tecnológico'],
            ['id' => '0612R014', 'nome' => 'Redes de computadores - Sequencial'],
            ['id' => '0613E012', 'nome' => 'Engenharia de software - Bacharelado'],
            ['id' => '0613E013', 'nome' => 'Engenharia de software - Tecnológico'],
            ['id' => '0613E014', 'nome' => 'Engenharia de software - Sequencial'],
            ['id' => '0613J012', 'nome' => 'Jogos digitais - Bacharelado'],
            ['id' => '0613J013', 'nome' => 'Jogos digitais - Tecnológico'],
            ['id' => '0613J014', 'nome' => 'Jogos digitais - Sequencial'],
            ['id' => '0614C012', 'nome' => 'Ciência da computação - Bacharelado'],
            ['id' => '0614C013', 'nome' => 'Ciência da computação - Tecnológico'],
            ['id' => '0614C014', 'nome' => 'Ciência da computação - Sequencial'],
            ['id' => '0615S013', 'nome' => 'Segurança da informação - Tecnológico'],
            ['id' => '0615S014', 'nome' => 'Segurança da informação - Sequencial'],
            ['id' => '0615S022', 'nome' => 'Sistemas de informação - Bacharelado'],
            ['id' => '0615S023', 'nome' => 'Sistemas de informação - Tecnológico'],
            ['id' => '0615S024', 'nome' => 'Sistemas de informação - Sequencial'],
            ['id' => '0615S032', 'nome' => 'Sistemas para internet - Bacharelado'],
            ['id' => '0615S033', 'nome' => 'Sistemas para internet - Tecnológico'],
            ['id' => '0615S034', 'nome' => 'Sistemas para internet - Sequencial'],
            ['id' => '0616E012', 'nome' => 'Engenharia de computação (DCN Computação] - Bacharelado'],
            ['id' => '0616S013', 'nome' => 'Sistemas embarcados - Tecnológico'],
            ['id' => '0688P012', 'nome' => 'Programas interdisciplinares abrangendo computação e Tecnologias da Informação e Comunicação (TIC] -'],
            ['id' => '0688P013', 'nome' => 'Programas interdisciplinares abrangendo computação e Tecnologias da Informação e Comunicação (TIC] -'],
            ['id' => '0710E012', 'nome' => 'Engenharia - Bacharelado'],
            ['id' => '0711B013', 'nome' => 'Biocombustíveis - Tecnológico'],
            ['id' => '0711E012', 'nome' => 'Engenharia bioquímica - Bacharelado'],
            ['id' => '0711E022', 'nome' => 'Engenharia de bioprocessos - Bacharelado'],
            ['id' => '0711E032', 'nome' => 'Engenharia de biotecnologia - Bacharelado'],
            ['id' => '0711E042', 'nome' => 'Engenharia de nanotecnologia - Bacharelado'],
            ['id' => '0711E052', 'nome' => 'Engenharia química - Bacharelado'],
            ['id' => '0712E012', 'nome' => 'Engenharia ambiental - Bacharelado'],
            ['id' => '0712E022', 'nome' => 'Engenharia ambiental e sanitária - Bacharelado'],
            ['id' => '0712G012', 'nome' => 'Gestão ambiental - Bacharelado'],
            ['id' => '0712G013', 'nome' => 'Gestão ambiental - Tecnológico'],
            ['id' => '0712G014', 'nome' => 'Gestão ambiental - Sequencial'],
            ['id' => '0712G023', 'nome' => 'Gestão de resíduos - Tecnológico'],
            ['id' => '0712G024', 'nome' => 'Gestão de resíduos - Sequencial'],
            ['id' => '0712S013', 'nome' => 'Saneamento ambiental - Tecnológico'],
            ['id' => '0713E013', 'nome' => 'Eletrotécnica industrial - Tecnológico'],
            ['id' => '0713E023', 'nome' => 'Energias renováveis - Tecnológico'],
            ['id' => '0713E032', 'nome' => 'Engenharia bioenergética - Bacharelado'],
            ['id' => '0713E042', 'nome' => 'Engenharia de energia - Bacharelado'],
            ['id' => '0713E052', 'nome' => 'Engenharia elétrica - Bacharelado'],
            ['id' => '0713E062', 'nome' => 'Engenharia nuclear - Bacharelado'],
            ['id' => '0713R013', 'nome' => 'Refrigeração e climatização - Tecnológico'],
            ['id' => '0713S012', 'nome' => 'Sistemas elétricos - Bacharelado'],
            ['id' => '0713S013', 'nome' => 'Sistemas elétricos - Tecnológico'],
            ['id' => '0713S014', 'nome' => 'Sistemas elétricos - Sequencial'],
            ['id' => '0714A013', 'nome' => 'Automação industrial - Tecnológico'],
            ['id' => '0714A014', 'nome' => 'Automação industrial - Sequencial'],
            ['id' => '0714E013', 'nome' => 'Eletrônica industrial - Tecnológico'],
            ['id' => '0714E022', 'nome' => 'Engenharia acústica - Bacharelado'],
            ['id' => '0714E032', 'nome' => 'Engenharia biomédica - Bacharelado'],
            ['id' => '0714E042', 'nome' => 'Engenharia de computação (DCN Engenharia] - Bacharelado'],
            ['id' => '0714E052', 'nome' => 'Engenharia de controle e automação - Bacharelado'],
            ['id' => '0714E062', 'nome' => 'Engenharia de informação - Bacharelado'],
            ['id' => '0714E072', 'nome' => 'Engenharia de telecomunicações - Bacharelado'],
            ['id' => '0714E082', 'nome' => 'Engenharia eletrônica - Bacharelado'],
            ['id' => '0714E092', 'nome' => 'Engenharia mecatrônica - Bacharelado'],
            ['id' => '0714G013', 'nome' => 'Gestão de telecomunicações - Tecnológico'],
            ['id' => '0714G014', 'nome' => 'Gestão de telecomunicações - Sequencial'],
            ['id' => '0714M013', 'nome' => 'Mecatrônica industrial - Tecnológico'],
            ['id' => '0714M014', 'nome' => 'Mecatrônica industrial - Sequencial'],
            ['id' => '0714R013', 'nome' => 'Redes de telecomunicações - Tecnológico'],
            ['id' => '0714S013', 'nome' => 'Sistemas biomédicos - Tecnológico'],
            ['id' => '0714S023', 'nome' => 'Sistemas de telecomunicações - Tecnológico'],
            ['id' => '0714S024', 'nome' => 'Sistemas de telecomunicações - Sequencial'],
            ['id' => '0714T013', 'nome' => 'Telemática - Tecnológico'],
            ['id' => '0714T014', 'nome' => 'Telemática - Sequencial'],
            ['id' => '0715E012', 'nome' => 'Engenharia física - Bacharelado'],
            ['id' => '0715E022', 'nome' => 'Engenharia mecânica - Bacharelado'],
            ['id' => '0715E032', 'nome' => 'Engenharia metalúrgica - Bacharelado'],
            ['id' => '0715F013', 'nome' => 'Fabricação mecânica - Tecnológico'],
            ['id' => '0715M013', 'nome' => 'Manutenção industrial - Tecnológico'],
            ['id' => '0715M014', 'nome' => 'Manutenção industrial - Sequencial'],
            ['id' => '0715M023', 'nome' => 'Mecânica de precisão - Tecnológico'],
            ['id' => '0715P013', 'nome' => 'Processos metalúrgicos - Tecnológico'],
            ['id' => '0715P014', 'nome' => 'Processos metalúrgicos - Sequencial'],
            ['id' => '0715S013', 'nome' => 'Soldagem - Tecnológico'],
            ['id' => '0715S014', 'nome' => 'Soldagem - Sequencial'],
            ['id' => '0716A013', 'nome' => 'Aeroespacial - Tecnológico'],
            ['id' => '0716C013', 'nome' => 'Construção naval - Tecnológico'],
            ['id' => '0716E012', 'nome' => 'Engenharia aeroespacial - Bacharelado'],
            ['id' => '0716E022', 'nome' => 'Engenharia aeronáutica - Bacharelado'],
            ['id' => '0716E023', 'nome' => 'Engenharia aeronáutica - Tecnológico'],
            ['id' => '0716E032', 'nome' => 'Engenharia automotiva - Bacharelado'],
            ['id' => '0716E042', 'nome' => 'Engenharia ferroviária e metroviária - Bacharelado'],
            ['id' => '0716E052', 'nome' => 'Engenharia naval - Bacharelado'],
            ['id' => '0716M013', 'nome' => 'Manutenção de aeronaves - Tecnológico'],
            ['id' => '0716M014', 'nome' => 'Manutenção de aeronaves - Sequencial'],
            ['id' => '0716S013', 'nome' => 'Sistemas automotivos - Tecnológico'],
            ['id' => '0716S023', 'nome' => 'Sistemas de navegação fluvial - Tecnológico'],
            ['id' => '0721A012', 'nome' => 'Alimentos - Bacharelado'],
            ['id' => '0721A013', 'nome' => 'Alimentos - Tecnológico'],
            ['id' => '0721A014', 'nome' => 'Alimentos - Sequencial'],
            ['id' => '0721E012', 'nome' => 'Engenharia de alimentos - Bacharelado'],
            ['id' => '0721L012', 'nome' => 'Laticínios - Bacharelado'],
            ['id' => '0721L013', 'nome' => 'Laticínios - Tecnológico'],
            ['id' => '0721P013', 'nome' => 'Processamento de carnes - Tecnológico'],
            ['id' => '0721P023', 'nome' => 'Produção de cachaça - Tecnológico'],
            ['id' => '0721P033', 'nome' => 'Produção sucroalcooleira - Tecnológico'],
            ['id' => '0721P034', 'nome' => 'Produção sucroalcooleira - Sequencial'],
            ['id' => '0721P043', 'nome' => 'Produção de cerveja - Tecnológico'],
            ['id' => '0722C013', 'nome' => 'Cerâmica - Tecnológico'],
            ['id' => '0722C023', 'nome' => 'Ciências dos materiais - Tecnológico'],
            ['id' => '0722C024', 'nome' => 'Ciências dos materiais - Sequencial'],
            ['id' => '0722E012', 'nome' => 'Engenharia de materiais - Bacharelado'],
            ['id' => '0722P013', 'nome' => 'Papel e celulose - Tecnológico'],
            ['id' => '0722P022', 'nome' => 'Polímeros - Bacharelado'],
            ['id' => '0722P023', 'nome' => 'Polímeros - Tecnológico'],
            ['id' => '0722P033', 'nome' => 'Produção joalheira - Tecnológico'],
            ['id' => '0722P043', 'nome' => 'Produção moveleira - Tecnológico'],
            ['id' => '0723E012', 'nome' => 'Engenharia têxtil - Bacharelado'],
            ['id' => '0723P013', 'nome' => 'Produção de vestuário - Tecnológico'],
            ['id' => '0723P022', 'nome' => 'Produção têxtil - Bacharelado'],
            ['id' => '0723P023', 'nome' => 'Produção têxtil - Tecnológico'],
            ['id' => '0724E012', 'nome' => 'Engenharia de minas - Bacharelado'],
            ['id' => '0724E022', 'nome' => 'Engenharia de petróleo - Bacharelado'],
            ['id' => '0724E032', 'nome' => 'Engenharia geológica - Bacharelado'],
            ['id' => '0724M013', 'nome' => 'Mineração - Tecnológico'],
            ['id' => '0724P013', 'nome' => 'Petróleo e gás - Tecnológico'],
            ['id' => '0724R013', 'nome' => 'Rochas ornamentais - Tecnológico'],
            ['id' => '0725E012', 'nome' => 'Engenharia de manufatura - Bacharelado'],
            ['id' => '0725E013', 'nome' => 'Engenharia de manufatura - Tecnológico'],
            ['id' => '0725E022', 'nome' => 'Engenharia de produção - Bacharelado'],
            ['id' => '0725E032', 'nome' => 'Engenharia industrial - Bacharelado'],
            ['id' => '0725P013', 'nome' => 'Produção gráfica - Tecnológico'],
            ['id' => '0725P023', 'nome' => 'Produção industrial - Tecnológico'],
            ['id' => '0731A013', 'nome' => 'Agrimensura - Tecnológico'],
            ['id' => '0731A022', 'nome' => 'Arquitetura e urbanismo - Bacharelado'],
            ['id' => '0731A023', 'nome' => 'Arquitetura e urbanismo - Tecnológico'],
            ['id' => '0731A024', 'nome' => 'Arquitetura e urbanismo - Sequencial'],
            ['id' => '0731E012', 'nome' => 'Engenharia cartográfica - Bacharelado'],
            ['id' => '0731E022', 'nome' => 'Engenharia de agrimensura - Bacharelado'],
            ['id' => '0731E024', 'nome' => 'Engenharia de agrimensura - Sequencial'],
            ['id' => '0731E032', 'nome' => 'Engenharia de agrimensura e cartográfica - Bacharelado'],
            ['id' => '0732C013', 'nome' => 'Construção de edifícios - Tecnológico'],
            ['id' => '0732C023', 'nome' => 'Controle de obras - Tecnológico'],
            ['id' => '0732C024', 'nome' => 'Controle de obras - Sequencial'],
            ['id' => '0732E012', 'nome' => 'Engenharia civil - Bacharelado'],
            ['id' => '0732E022', 'nome' => 'Engenharia de recursos hídricos - Bacharelado'],
            ['id' => '0732E032', 'nome' => 'Engenharia de transportes - Bacharelado'],
            ['id' => '0732E042', 'nome' => 'Engenharia portuária - Bacharelado'],
            ['id' => '0732E053', 'nome' => 'Estradas - Tecnológico'],
            ['id' => '0732G013', 'nome' => 'Gestão de recursos hídricos - Tecnológico'],
            ['id' => '0732M013', 'nome' => 'Material de construção - Tecnológico'],
            ['id' => '0788P012', 'nome' => 'Programas interdisciplinares abrangendo engenharia, produção e construção - Bacharelado'],
            ['id' => '0811A012', 'nome' => 'Agroecologia - Bacharelado'],
            ['id' => '0811A013', 'nome' => 'Agroecologia - Tecnológico'],
            ['id' => '0811A022', 'nome' => 'Agroindústria - Bacharelado'],
            ['id' => '0811A023', 'nome' => 'Agroindústria - Tecnológico'],
            ['id' => '0811A024', 'nome' => 'Agroindústria - Sequencial'],
            ['id' => '0811A032', 'nome' => 'Agronegócio - Bacharelado'],
            ['id' => '0811A033', 'nome' => 'Agronegócio - Tecnológico'],
            ['id' => '0811A042', 'nome' => 'Agronomia - Bacharelado'],
            ['id' => '0811A043', 'nome' => 'Agronomia - Tecnológico'],
            ['id' => '0811A053', 'nome' => 'Agropecuária - Tecnológico'],
            ['id' => '0811C013', 'nome' => 'Cafeicultura - Tecnológico'],
            ['id' => '0811E012', 'nome' => 'Engenharia agrícola - Bacharelado'],
            ['id' => '0811E013', 'nome' => 'Engenharia agrícola - Tecnológico'],
            ['id' => '0811E022', 'nome' => 'Engenharia de biossistemas - Bacharelado'],
            ['id' => '0811F013', 'nome' => 'Fruticultura - Tecnológico'],
            ['id' => '0811F014', 'nome' => 'Fruticultura - Sequencial'],
            ['id' => '0811I013', 'nome' => 'Irrigação e drenagem - Tecnológico'],
            ['id' => '0811M013', 'nome' => 'Manejo da produção agrícola - Tecnológico'],
            ['id' => '0811V012', 'nome' => 'Viticultura e enologia - Bacharelado'],
            ['id' => '0811V013', 'nome' => 'Viticultura e enologia - Tecnológico'],
            ['id' => '0811Z012', 'nome' => 'Zootecnia - Bacharelado'],
            ['id' => '0811Z013', 'nome' => 'Zootecnia - Tecnológico'],
            ['id' => '0811Z014', 'nome' => 'Zootecnia - Sequencial'],
            ['id' => '0812H013', 'nome' => 'Horticultura - Tecnológico'],
            ['id' => '0821E012', 'nome' => 'Engenharia florestal - Bacharelado'],
            ['id' => '0821E013', 'nome' => 'Engenharia florestal - Tecnológico'],
            ['id' => '0821S013', 'nome' => 'Silvicultura - Tecnológico'],
            ['id' => '0831A012', 'nome' => 'Aquicultura - Bacharelado'],
            ['id' => '0831A013', 'nome' => 'Aquicultura - Tecnológico'],
            ['id' => '0831A014', 'nome' => 'Aquicultura - Sequencial'],
            ['id' => '0831E012', 'nome' => 'Engenharia de pesca - Bacharelado'],
            ['id' => '0831P013', 'nome' => 'Produção pesqueira - Tecnológico'],
            ['id' => '0841M012', 'nome' => 'Medicina veterinária - Bacharelado'],
            ['id' => '0841M013', 'nome' => 'Medicina veterinária - Tecnológico'],
            ['id' => '0841M014', 'nome' => 'Medicina veterinária - Sequencial'],
            ['id' => '0888P012', 'nome' => 'Programas interdisciplinares abrangendo agricultura, silvicultura, pesca e veterinária - Bacharelado'],
            ['id' => '0911O012', 'nome' => 'Odontologia - Bacharelado'],
            ['id' => '0911O014', 'nome' => 'Odontologia - Sequencial'],
            ['id' => '0912M012', 'nome' => 'Medicina - Bacharelado'],
            ['id' => '0912M013', 'nome' => 'Medicina - Tecnológico'],
            ['id' => '0912M014', 'nome' => 'Medicina - Sequencial'],
            ['id' => '0913E012', 'nome' => 'Enfermagem - Bacharelado'],
            ['id' => '0913E014', 'nome' => 'Enfermagem - Sequencial'],
            ['id' => '0914A013', 'nome' => 'Análises clínicas e toxicológicas - Tecnológico'],
            ['id' => '0914A014', 'nome' => 'Análises clínicas e toxicológicas - Sequencial'],
            ['id' => '0914B012', 'nome' => 'Biomedicina - Bacharelado'],
            ['id' => '0914B014', 'nome' => 'Biomedicina - Sequencial'],
            ['id' => '0914O013', 'nome' => 'Oftálmica - Tecnológico'],
            ['id' => '0914O022', 'nome' => 'Optometria - Bacharelado'],
            ['id' => '0914O023', 'nome' => 'Optometria - Tecnológico'],
            ['id' => '0914P013', 'nome' => 'Prótese e órtese - Tecnológico'],
            ['id' => '0914P014', 'nome' => 'Prótese e órtese - Sequencial'],
            ['id' => '0914R013', 'nome' => 'Radiologia - Tecnológico'],
            ['id' => '0914R014', 'nome' => 'Radiologia - Sequencial'],
            ['id' => '0915E012', 'nome' => 'Educação física - Bacharelado'],
            ['id' => '0915E014', 'nome' => 'Educação física - Sequencial'],
            ['id' => '0915F012', 'nome' => 'Fisioterapia - Bacharelado'],
            ['id' => '0915F022', 'nome' => 'Fonoaudiologia - Bacharelado'],
            ['id' => '0915N012', 'nome' => 'Nutrição - Bacharelado'],
            ['id' => '0915N013', 'nome' => 'Nutrição - Tecnológico'],
            ['id' => '0915N014', 'nome' => 'Nutrição - Sequencial'],
            ['id' => '0915P012', 'nome' => 'Podologia - Bacharelado'],
            ['id' => '0915P013', 'nome' => 'Podologia - Tecnológico'],
            ['id' => '0915T012', 'nome' => 'Terapia ocupacional - Bacharelado'],
            ['id' => '0916F012', 'nome' => 'Farmácia - Bacharelado'],
            ['id' => '0916F013', 'nome' => 'Farmácia - Tecnológico'],
            ['id' => '0916F014', 'nome' => 'Farmácia - Sequencial'],
            ['id' => '0917M012', 'nome' => 'Musicoterapia - Bacharelado'],
            ['id' => '0917P012', 'nome' => 'Práticas integrativas - Bacharelado'],
            ['id' => '0917P013', 'nome' => 'Práticas integrativas - Tecnológico'],
            ['id' => '0917P014', 'nome' => 'Práticas integrativas - Sequencial'],
            ['id' => '0918S012', 'nome' => 'Saúde coletiva - Bacharelado'],
            ['id' => '0918S013', 'nome' => 'Saúde coletiva - Tecnológico'],
            ['id' => '0918S014', 'nome' => 'Saúde coletiva - Sequencial'],
            ['id' => '0918S022', 'nome' => 'Saúde pública - Bacharelado'],
            ['id' => '0918S023', 'nome' => 'Saúde pública - Tecnológico'],
            ['id' => '0918S024', 'nome' => 'Saúde pública - Sequencial'],
            ['id' => '0921A014', 'nome' => 'Assistência a idosos e a deficientes - Sequencial'],
            ['id' => '0921G012', 'nome' => 'Gerontologia - Bacharelado'],
            ['id' => '0921G013', 'nome' => 'Gerontologia - Tecnológico'],
            ['id' => '0921G014', 'nome' => 'Gerontologia - Sequencial'],
            ['id' => '0923S012', 'nome' => 'Serviço social - Bacharelado'],
            ['id' => '0923S013', 'nome' => 'Serviço social - Tecnológico'],
            ['id' => '0923S014', 'nome' => 'Serviço social - Sequencial'],
            ['id' => '0988P012', 'nome' => 'Programas interdisciplinares abrangendo saúde e bem-estar - Bacharelado'],
            ['id' => '0988P013', 'nome' => 'Programas interdisciplinares abrangendo saúde e bem-estar - Tecnológico'],
            ['id' => '0988P014', 'nome' => 'Programas interdisciplinares abrangendo saúde e bem-estar - Sequencial'],
            ['id' => '1011E012', 'nome' => 'Economia doméstica - Bacharelado'],
            ['id' => '1012E012', 'nome' => 'Estética e cosmética - Bacharelado'],
            ['id' => '1012E013', 'nome' => 'Estética e cosmética - Tecnológico'],
            ['id' => '1012E014', 'nome' => 'Estética e cosmética - Sequencial'],
            ['id' => '1013G012', 'nome' => 'Gastronomia - Bacharelado'],
            ['id' => '1013G013', 'nome' => 'Gastronomia - Tecnológico'],
            ['id' => '1013G014', 'nome' => 'Gastronomia - Sequencial'],
            ['id' => '1014F013', 'nome' => 'Formação de técnicos e treinadores esportivos - Tecnológico'],
            ['id' => '1014F014', 'nome' => 'Formação de técnicos e treinadores esportivos - Sequencial'],
            ['id' => '1014G012', 'nome' => 'Gestão desportiva e de lazer - Bacharelado'],
            ['id' => '1014G013', 'nome' => 'Gestão desportiva e de lazer - Tecnológico'],
            ['id' => '1014G014', 'nome' => 'Gestão desportiva e de lazer - Sequencial'],
            ['id' => '1015E013', 'nome' => 'Eventos - Tecnológico'],
            ['id' => '1015E014', 'nome' => 'Eventos - Sequencial'],
            ['id' => '1015H012', 'nome' => 'Hotelaria - Bacharelado'],
            ['id' => '1015H013', 'nome' => 'Hotelaria - Tecnológico'],
            ['id' => '1015H014', 'nome' => 'Hotelaria - Sequencial'],
            ['id' => '1015T012', 'nome' => 'Turismo - Bacharelado'],
            ['id' => '1015T013', 'nome' => 'Turismo - Tecnológico'],
            ['id' => '1015T014', 'nome' => 'Turismo - Sequencial'],
            ['id' => '1022S012', 'nome' => 'Segurança no trabalho - Bacharelado'],
            ['id' => '1022S013', 'nome' => 'Segurança no trabalho - Tecnológico'],
            ['id' => '1022S014', 'nome' => 'Segurança no trabalho - Sequencial'],
            ['id' => '1031C012', 'nome' => 'Ciências militares - Bacharelado'],
            ['id' => '1032I013', 'nome' => 'Investigação e perícia - Tecnológico'],
            ['id' => '1032I014', 'nome' => 'Investigação e perícia - Sequencial'],
            ['id' => '1032S013', 'nome' => 'Segurança no trânsito - Tecnológico'],
            ['id' => '1032S014', 'nome' => 'Segurança no trânsito - Sequencial'],
            ['id' => '1032S023', 'nome' => 'Segurança privada - Tecnológico'],
            ['id' => '1032S024', 'nome' => 'Segurança privada - Sequencial'],
            ['id' => '1032S032', 'nome' => 'Segurança pública - Bacharelado'],
            ['id' => '1032S033', 'nome' => 'Segurança pública - Tecnológico'],
            ['id' => '1032S034', 'nome' => 'Segurança pública - Sequencial'],
            ['id' => '1032S043', 'nome' => 'Serviços penais - Tecnológico'],
            ['id' => '1032S044', 'nome' => 'Serviços penais - Sequencial'],
            ['id' => '1041C012', 'nome' => 'Ciências aeronáuticas - Bacharelado'],
            ['id' => '1041C013', 'nome' => 'Ciências aeronáuticas - Tecnológico'],
            ['id' => '1041C014', 'nome' => 'Ciências aeronáuticas - Sequencial'],
            ['id' => '1041G013', 'nome' => 'Gestão portuária - Tecnológico'],
            ['id' => '1041G014', 'nome' => 'Gestão portuária - Sequencial'],
            ['id' => '1041T013', 'nome' => 'Transporte aéreo - Tecnológico'],
            ['id' => '1041T023', 'nome' => 'Transporte terrestre - Tecnológico'],
            ['id' => '1041T024', 'nome' => 'Transporte terrestre - Sequencial']
        ]);
    }
}
