<?php

namespace Database\Seeders\Helpers;

use Illuminate\Database\Seeder;
use App\Models\Helpers\CursoTecnico;

class CursoTecnicoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CursoTecnico::insert([
            ['id' => '1001', 'nome' => 'Agente Comunitário de Saúde'],
            ['id' => '1002', 'nome' => 'Análises clínicas'],
            ['id' => '1004', 'nome' => 'Citopatologia'],
            ['id' => '1005', 'nome' => 'Controle Ambiental'],
            ['id' => '1006', 'nome' => 'Enfermagem'],
            ['id' => '1007', 'nome' => 'Equipamentos Biomédicos'],
            ['id' => '1008', 'nome' => 'Estética'],
            ['id' => '1009', 'nome' => 'Farmácia'],
            ['id' => '1010', 'nome' => 'Gerência de Saúde'],
            ['id' => '1011', 'nome' => 'Hemoterapia'],
            ['id' => '1012', 'nome' => 'Saúde Bucal'],
            ['id' => '1013', 'nome' => 'Imagem Pessoal '],
            ['id' => '1014', 'nome' => 'Imobilizações Ortopédicas'],
            ['id' => '1015', 'nome' => 'Massoterapia '],
            ['id' => '1016', 'nome' => 'Meio Ambiente '],
            ['id' => '1017', 'nome' => 'Meteorologia '],
            ['id' => '1018', 'nome' => 'Nutrição e Dietética'],
            ['id' => '1019', 'nome' => 'Óptica '],
            ['id' => '1020', 'nome' => 'Órteses e Próteses'],
            ['id' => '1021', 'nome' => 'Podologia'],
            ['id' => '1022', 'nome' => 'Prótese Dentária '],
            ['id' => '1023', 'nome' => 'Radiologia '],
            ['id' => '1024', 'nome' => 'Dependência química'],
            ['id' => '1025', 'nome' => 'Reciclagem'],
            ['id' => '1026', 'nome' => 'Registros e Informações em Saúde'],
            ['id' => '1028', 'nome' => 'Vigilância em Saúde'],
            ['id' => '1029', 'nome' => 'Cuidados de Idosos'],
            ['id' => '1030', 'nome' => 'Necropsia'],
            ['id' => '1031', 'nome' => 'Optometria'],
            ['id' => '1032', 'nome' => 'Terapias Holísticas'],
            ['id' => '1033', 'nome' => ' Veterinária'],
            ['id' => '1999', 'nome' => 'Outros - Eixo Ambiente e Saúde'],
            ['id' => '2029', 'nome' => 'Alimentação Escolar'],
            ['id' => '2030', 'nome' => 'Biblioteconomia'],
            ['id' => '2031', 'nome' => 'Infraestrutura escolar'],
            ['id' => '2032', 'nome' => 'Multimeios Didáticos'],
            ['id' => '2033', 'nome' => 'Desenvolvimento Comunitário'],
            ['id' => '2034', 'nome' => 'Secretaria Escolar'],
            ['id' => '2035', 'nome' => 'Brinquedoteca'],
            ['id' => '2036', 'nome' => 'Produção de materiais didáticos bilíngues em Libras/Língua Portuguesa'],
            ['id' => '2037', 'nome' => 'Tradução e Interpretação de Libras'],
            ['id' => '2038', 'nome' => 'Treinamento e Instrução de Cães-Guias'],
            ['id' => '2039', 'nome' => 'Laboratório de Ciências da Natureza'],
            ['id' => '2040', 'nome' => ' Arquivo'],
            ['id' => '2999', 'nome' => 'Outros - Eixo Desenvolvimento educacional e social'],
            ['id' => '3036', 'nome' => 'Automação Industrial'],
            ['id' => '3037', 'nome' => 'Eletroeletrônica '],
            ['id' => '3038', 'nome' => 'Eletromecânica '],
            ['id' => '3039', 'nome' => 'Eletrônica '],
            ['id' => '3040', 'nome' => 'Eletrotécnica '],
            ['id' => '3041', 'nome' => 'Manutenção Automotiva'],
            ['id' => '3042', 'nome' => 'Manutenção de Máquinas Navais'],
            ['id' => '3043', 'nome' => 'Mecânica '],
            ['id' => '3044', 'nome' => 'Mecatrônica '],
            ['id' => '3045', 'nome' => 'Metalurgia '],
            ['id' => '3048', 'nome' => 'Refrigeração e Climatização'],
            ['id' => '3049', 'nome' => 'Sistemas a Gás '],
            ['id' => '3050', 'nome' => 'Manutenção Aeronáutica em Aviônicos'],
            ['id' => '3051', 'nome' => 'Manutenção Aeronáutica em Célula'],
            ['id' => '3052', 'nome' => 'Manutenção Aeronáutica em Grupo Motopropulsor'],
            ['id' => '3053', 'nome' => 'Manutenção de Máquinas Pesadas'],
            ['id' => '3054', 'nome' => 'Manutenção de Sistemas Metroferroviários'],
            ['id' => '3055', 'nome' => 'Mecânica de Precisão'],
            ['id' => '3056', 'nome' => 'Metrologia'],
            ['id' => '3058', 'nome' => 'Sistemas de Energia Renovável'],
            ['id' => '3059', 'nome' => 'Soldagem'],
            ['id' => '3060', 'nome' => 'Manutenção de Máquinas Industriais'],
            ['id' => '3061', 'nome' => 'Ferramentaria'],
            ['id' => '3062', 'nome' => 'Fundição'],
            ['id' => '3063', 'nome' => 'Instrumentação Industrial'],
            ['id' => '3064', 'nome' => 'Fabricação Mecânica '],
            ['id' => '3999', 'nome' => 'Outros - Eixo Controle e Processos Industriais'],
            ['id' => '4050', 'nome' => 'Administração '],
            ['id' => '4051', 'nome' => 'Comércio '],
            ['id' => '4052', 'nome' => 'Comércio Exterior'],
            ['id' => '4053', 'nome' => 'Contabilidade '],
            ['id' => '4054', 'nome' => 'Cooperativismo '],
            ['id' => '4055', 'nome' => 'Finanças '],
            ['id' => '4056', 'nome' => 'Logística '],
            ['id' => '4057', 'nome' => 'Marketing '],
            ['id' => '4058', 'nome' => 'Qualidade '],
            ['id' => '4059', 'nome' => 'Recursos Humanos'],
            ['id' => '4060', 'nome' => 'Secretariado '],
            ['id' => '4061', 'nome' => 'Seguros'],
            ['id' => '4062', 'nome' => 'Condomínio'],
            ['id' => '4063', 'nome' => 'Serviços Públicos'],
            ['id' => '4064', 'nome' => 'Transações Imobiliárias'],
            ['id' => '4065', 'nome' => 'Vendas '],
            ['id' => '4066', 'nome' => 'Serviços Jurídicos'],
            ['id' => '4999', 'nome' => 'Outros - Eixo Gestão e Negócios'],
            ['id' => '5066', 'nome' => 'Agenciamento de Viagem'],
            ['id' => '5067', 'nome' => 'Gastronomia '],
            ['id' => '5068', 'nome' => 'Eventos '],
            ['id' => '5069', 'nome' => 'Guia de Turismo '],
            ['id' => '5070', 'nome' => 'Hospedagem '],
            ['id' => '5071', 'nome' => 'Lazer '],
            ['id' => '5072', 'nome' => 'Serviços de Restaurante e Bar'],
            ['id' => '5999', 'nome' => 'Outros - Eixo Turismo, hospitalidade e Lazer'],
            ['id' => '6073', 'nome' => 'Informática '],
            ['id' => '6074', 'nome' => 'Informática para Internet'],
            ['id' => '6075', 'nome' => 'Manutenção e Suporte em Informática'],
            ['id' => '6076', 'nome' => 'Programação de Jogos Digitais'],
            ['id' => '6077', 'nome' => 'Redes de Computadores'],
            ['id' => '6078', 'nome' => 'Sistemas de Comutação'],
            ['id' => '6079', 'nome' => 'Sistemas de Transmissão'],
            ['id' => '6080', 'nome' => 'Telecomunicações '],
            ['id' => '6081', 'nome' => 'Computação Gráfica'],
            ['id' => '6082', 'nome' => 'Desenvolvimento de Sistemas'],
            ['id' => '6999', 'nome' => 'Outros - Eixo Informação e Comunicação'],
            ['id' => '7081', 'nome' => 'Aeroportuário '],
            ['id' => '7082', 'nome' => 'Agrimensura '],
            ['id' => '7083', 'nome' => 'Carpintaria'],
            ['id' => '7084', 'nome' => 'Desenho de Construção Civil'],
            ['id' => '7085', 'nome' => 'Edificações '],
            ['id' => '7086', 'nome' => 'Estradas'],
            ['id' => '7087', 'nome' => 'Geodésia e Cartografia'],
            ['id' => '7088', 'nome' => 'Geoprocessamento '],
            ['id' => '7089', 'nome' => 'Hidrologia '],
            ['id' => '7091', 'nome' => 'Portos '],
            ['id' => '7092', 'nome' => 'Saneamento '],
            ['id' => '7093', 'nome' => 'Trânsito '],
            ['id' => '7094', 'nome' => 'Transporte Aquaviário'],
            ['id' => '7095', 'nome' => 'Transporte de Cargas'],
            ['id' => '7096', 'nome' => 'Transporte Dutoviário'],
            ['id' => '7097', 'nome' => 'Transporte Metroferroviário'],
            ['id' => '7098', 'nome' => 'Transporte Rodoviário'],
            ['id' => '7999', 'nome' => 'Outros - Eixo Infra-Estrutura'],
            ['id' => '8099', 'nome' => 'Comunicações Aeronáuticas'],
            ['id' => '8100', 'nome' => 'Controle de Tráfego Aéreo'],
            ['id' => '8101', 'nome' => 'Desenho Militar'],
            ['id' => '8102', 'nome' => 'Eletricidade e Instrumentos Aeronáuticos'],
            ['id' => '8103', 'nome' => 'Equipamentos de Voo'],
            ['id' => '8104', 'nome' => 'Estrutura e Pintura de Aeronaves'],
            ['id' => '8105', 'nome' => 'Fotointeligência'],
            ['id' => '8106', 'nome' => 'Guarda e Segurança'],
            ['id' => '8107', 'nome' => 'Hidrografia'],
            ['id' => '8108', 'nome' => 'Informações Aeronáuticas'],
            ['id' => '8109', 'nome' => 'Manobras e Equipamentos de Convés'],
            ['id' => '8110', 'nome' => 'Material Bélico'],
            ['id' => '8111', 'nome' => 'Mergulho'],
            ['id' => '8112', 'nome' => 'Operação de Radar'],
            ['id' => '8113', 'nome' => 'Operação de Sonar'],
            ['id' => '8114', 'nome' => 'Operações de Engenharia Militar'],
            ['id' => '8115', 'nome' => 'Preparação Física e Desportiva Militar'],
            ['id' => '8116', 'nome' => 'Sensores de Aviação'],
            ['id' => '8117', 'nome' => 'Sinais Navais'],
            ['id' => '8118', 'nome' => 'Sinalização Náutica'],
            ['id' => '8119', 'nome' => 'Suprimento'],
            ['id' => '8126', 'nome' => 'Comunicações Navais'],
            ['id' => '8130', 'nome' => 'Mecânica de Aeronaves '],
            ['id' => '8133', 'nome' => 'Bombeiro Aeronáutico'],
            ['id' => '8999', 'nome' => 'Outros - Eixo Militar'],
            ['id' => '9120', 'nome' => 'Alimentos '],
            ['id' => '9121', 'nome' => 'Agroindústria '],
            ['id' => '9123', 'nome' => 'Cervejaria'],
            ['id' => '9124', 'nome' => 'Confeitaria '],
            ['id' => '9125', 'nome' => 'Panificação '],
            ['id' => '9126', 'nome' => 'Processamento de Pescado'],
            ['id' => '9127', 'nome' => 'Viticultura e Enologia'],
            ['id' => '9999', 'nome' => 'Outros - Eixo Produção Alimentícia'],
            ['id' => '10128', 'nome' => 'Artes Circenses'],
            ['id' => '10129', 'nome' => 'Teatro'],
            ['id' => '10130', 'nome' => 'Artes Visuais '],
            ['id' => '10131', 'nome' => 'Artesanato '],
            ['id' => '10132', 'nome' => 'Canto '],
            ['id' => '10133', 'nome' => 'Composição e Arranjo'],
            ['id' => '10134', 'nome' => 'Design Gráfico'],
            ['id' => '10135', 'nome' => 'Conservação e Restauro'],
            ['id' => '10136', 'nome' => 'Dança'],
            ['id' => '10137', 'nome' => 'Design de Calçados'],
            ['id' => '10138', 'nome' => 'Design de Embalagens'],
            ['id' => '10139', 'nome' => 'Design de Interiores '],
            ['id' => '10140', 'nome' => 'Design de Jóias'],
            ['id' => '10141', 'nome' => 'Design de Móveis '],
            ['id' => '10142', 'nome' => 'Documentação Musical'],
            ['id' => '10143', 'nome' => 'Fabricação de Instrumentos Musicais'],
            ['id' => '10144', 'nome' => 'Instrumento Musical (nome do instrumento]'],
            ['id' => '10145', 'nome' => 'Modelagem do Vestuário'],
            ['id' => '10146', 'nome' => 'Multimídia '],
            ['id' => '10147', 'nome' => 'Paisagismo '],
            ['id' => '10148', 'nome' => 'Processos Fotográficos'],
            ['id' => '10149', 'nome' => 'Produção de Áudio e Vídeo'],
            ['id' => '10150', 'nome' => 'Produção de Moda '],
            ['id' => '10151', 'nome' => 'Publicidade'],
            ['id' => '10152', 'nome' => 'Rádio e Televisão'],
            ['id' => '10153', 'nome' => 'Regência '],
            ['id' => '10154', 'nome' => 'Cenografia'],
            ['id' => '10155', 'nome' => 'Museologia'],
            ['id' => '10156', 'nome' => 'Processos Fonográficos'],
            ['id' => '10157', 'nome' => 'Figurino Cênico'],
            ['id' => '10158', 'nome' => 'Design de Moda'],
            ['id' => '10159', 'nome' => 'Estilismo e Coordenação de Moda'],
            ['id' => '10160', 'nome' => 'Produção Cultural'],
            ['id' => '10999', 'nome' => 'Outros - Eixo Produção Cultural e Design'],
            ['id' => '11154', 'nome' => 'Açúcar e Álcool '],
            ['id' => '11155', 'nome' => 'Biocombustíveis'],
            ['id' => '11156', 'nome' => 'Calçados '],
            ['id' => '11157', 'nome' => 'Celulose e Papel '],
            ['id' => '11158', 'nome' => 'Cerâmica '],
            ['id' => '11159', 'nome' => 'Construção Naval '],
            ['id' => '11160', 'nome' => 'Curtimento '],
            ['id' => '11162', 'nome' => 'Impressão Rotográfica e Flexográfica'],
            ['id' => '11163', 'nome' => 'Impressão Offset '],
            ['id' => '11164', 'nome' => 'Joalheria'],
            ['id' => '11165', 'nome' => 'Móveis '],
            ['id' => '11166', 'nome' => 'Petróleo e Gás '],
            ['id' => '11167', 'nome' => 'Plásticos '],
            ['id' => '11169', 'nome' => 'Têxtil'],
            ['id' => '11170', 'nome' => 'Vestuário '],
            ['id' => '11171', 'nome' => 'Processos Gráficos'],
            ['id' => '11172', 'nome' => 'Análises Químicas'],
            ['id' => '11173', 'nome' => 'Biotecnologia'],
            ['id' => '11174', 'nome' => 'Petroquímica'],
            ['id' => '11175', 'nome' => 'Química'],
            ['id' => '11176', 'nome' => 'Planejamento e Controle da Produção'],
            ['id' => '11177', 'nome' => 'Vidros'],
            ['id' => '11178', 'nome' => 'Processamento da Madeira'],
            ['id' => '11999', 'nome' => 'Outros - Eixo Produção Industrial'],
            ['id' => '12171', 'nome' => 'Agricultura '],
            ['id' => '12172', 'nome' => 'Agroecologia'],
            ['id' => '12173', 'nome' => 'Agronegócio '],
            ['id' => '12174', 'nome' => 'Agropecuária '],
            ['id' => '12175', 'nome' => 'Aquicultura '],
            ['id' => '12176', 'nome' => 'Cafeicultura'],
            ['id' => '12178', 'nome' => 'Florestas '],
            ['id' => '12179', 'nome' => 'Fruticultura'],
            ['id' => '12180', 'nome' => 'Geologia '],
            ['id' => '12181', 'nome' => 'Mineração '],
            ['id' => '12182', 'nome' => 'Pesca'],
            ['id' => '12183', 'nome' => 'Recursos Minerais '],
            ['id' => '12184', 'nome' => 'Recursos Pesqueiros'],
            ['id' => '12185', 'nome' => 'Zootecnia '],
            ['id' => '12187', 'nome' => 'Pós-Colheita'],
            ['id' => '12188', 'nome' => 'Apicultura '],
            ['id' => '12999', 'nome' => 'Outros - Eixo Recursos Naturais'],
            ['id' => '13181', 'nome' => 'Defesa Civil'],
            ['id' => '13182', 'nome' => 'Segurança do Trabalho'],
            ['id' => '13183', 'nome' => 'Prevenção e Combate a Incêndios'],
            ['id' => '13999', 'nome' => 'Outros - Eixo Segurança']
        ]);
    }
}
