<?php

namespace Database\Seeders\Helpers;

use Illuminate\Database\Seeder;
use App\Models\Helpers\IndigenousLanguage;

class IndigenousLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        IndigenousLanguage::insert([
            ['id' => '1', 'name' => 'Aikaná/ Aikanã'],
            ['id' => '2', 'name' => 'Ajuru/ Wayoro, Ajurú'],
            ['id' => '4', 'name' => 'Suruí do Pará/ Suruí do Tocantins/ Aikewara'],
            ['id' => '5', 'name' => 'Xavánte/ Xavante'],
            ['id' => '6', 'name' => 'Xerénte'],
            ['id' => '7', 'name' => 'Amanayé'],
            ['id' => '10', 'name' => 'Apalaí'],
            ['id' => '11', 'name' => 'Apiaká'],
            ['id' => '12', 'name' => 'Apinayé'],
            ['id' => '13', 'name' => 'Apurinã'],
            ['id' => '14', 'name' => 'Arapáso'],
            ['id' => '15', 'name' => 'Arara do Acre, Shawãdawa '],
            ['id' => '17', 'name' => 'Araweté'],
            ['id' => '18', 'name' => 'Arikapú/ Jabutí'],
            ['id' => '19', 'name' => 'Aruá'],
            ['id' => '20', 'name' => 'Asuriní do Tocantins '],
            ['id' => '21', 'name' => 'Asuriní do Xingu'],
            ['id' => '22', 'name' => 'Ava-Canoeiro/ Avá-Canoeiro, Avá, Canoeiro'],
            ['id' => '23', 'name' => 'Awetí'],
            ['id' => '24', 'name' => 'Bakairí'],
            ['id' => '25', 'name' => 'Banawá'],
            ['id' => '26', 'name' => 'Baníwa/ Tapiira Tapuya, Kawa Tapuya '],
            ['id' => '28', 'name' => 'Bará'],
            ['id' => '29', 'name' => 'Baré'],
            ['id' => '30', 'name' => 'Boróro'],
            ['id' => '31', 'name' => 'Cinta Larga/ Cinta-Larga'],
            ['id' => '32', 'name' => 'Dení'],
            ['id' => '33', 'name' => 'Desána'],
            ['id' => '34', 'name' => 'Dâw'],
            ['id' => '35', 'name' => 'Galibí do Oiapoque, Galibí (Ka’ríña]'],
            ['id' => '36', 'name' => 'Gavião (Ikõro, Digüt], Gavião de Rondônia/ Ikolen'],
            ['id' => '37', 'name' => 'Guajá'],
            ['id' => '38', 'name' => 'Guaraní Kaiowá/ Guarani Kayová '],
            ['id' => '39', 'name' => 'Guaraní Mbyá'],
            ['id' => '40', 'name' => 'Guaraní Nhandéva'],
            ['id' => '42', 'name' => 'Guató'],
            ['id' => '43', 'name' => 'Hixkaryána'],
            ['id' => '45', 'name' => 'Ingarikó'],
            ['id' => '46', 'name' => 'Irántxe'],
            ['id' => '47', 'name' => 'Djeoromitxí/ Jabotí/ Jabutí'],
            ['id' => '48', 'name' => 'Jarawára'],
            ['id' => '49', 'name' => 'Yamináwa'],
            ['id' => '50', 'name' => 'Javaé'],
            ['id' => '51', 'name' => 'Jurúna/ Yudjá'],
            ['id' => '52', 'name' => 'Ka\'apor/ Urubu, Ka’apór'],
            ['id' => '53', 'name' => 'Kadiwéu'],
            ['id' => '58', 'name' => 'Kalapálo'],
            ['id' => '59', 'name' => 'Kamayurá'],
            ['id' => '60', 'name' => 'Ashanínka/ Axanínka'],
            ['id' => '61', 'name' => 'Kanamarí'],
            ['id' => '62', 'name' => 'Kanoé/ Kanoê'],
            ['id' => '63', 'name' => 'Karajá '],
            ['id' => '64', 'name' => 'Karapanã'],
            ['id' => '65', 'name' => 'Karitiána'],
            ['id' => '66', 'name' => 'Arara de Rondônia/ Káro'],
            ['id' => '67', 'name' => 'Katawixí'],
            ['id' => '68', 'name' => 'Katukína do Acre'],
            ['id' => '69', 'name' => 'Katukína'],
            ['id' => '76', 'name' => 'Uru-Eu-Wau-Wau/ Uruewawau '],
            ['id' => '77', 'name' => 'Kaxararí'],
            ['id' => '78', 'name' => 'Kaxinawá'],
            ['id' => '80', 'name' => 'Kayabí'],
            ['id' => '81', 'name' => 'Gorotire (Kayapó]'],
            ['id' => '82', 'name' => 'Kararaô (Kayapó]'],
            ['id' => '83', 'name' => 'Kokraimoro (Kayapó]'],
            ['id' => '84', 'name' => 'Kubenkrngkegn (Kayapó]'],
            ['id' => '85', 'name' => 'Menkrangnoti (Kayapó]'],
            ['id' => '86', 'name' => 'Mentuktíre, Txukahamae (Kayapó]'],
            ['id' => '87', 'name' => 'Xikrin (Kayapó]'],
            ['id' => '90', 'name' => 'Kokáma '],
            ['id' => '91', 'name' => 'Korúbo'],
            ['id' => '92', 'name' => 'Krenák'],
            ['id' => '93', 'name' => 'Kubéo, Kubewa'],
            ['id' => '94', 'name' => 'Kuikúro'],
            ['id' => '95', 'name' => 'Kulína Madijá/ Kulina, Kulína Madihá (Madija]'],
            ['id' => '96', 'name' => 'Kuruáya'],
            ['id' => '99', 'name' => 'Makuráp'],
            ['id' => '100', 'name' => 'Makuxí'],
            ['id' => '102', 'name' => 'Marúbo'],
            ['id' => '103', 'name' => 'Matipú'],
            ['id' => '104', 'name' => 'Matís'],
            ['id' => '105', 'name' => 'Matsés'],
            ['id' => '106', 'name' => 'Mawé'],
            ['id' => '107', 'name' => 'Maxakalí'],
            ['id' => '108', 'name' => 'Yekuána, Mayongong, Makiritáre,'],
            ['id' => '109', 'name' => 'Mehináku'],
            ['id' => '110', 'name' => 'Sakurabiat/ Kampé'],
            ['id' => '111', 'name' => 'Mondé, Tupí-Mondé'],
            ['id' => '112', 'name' => 'Mundurukú'],
            ['id' => '113', 'name' => 'Múra'],
            ['id' => '114', 'name' => 'Mynky/ Mynký, Meky, Menky, Menki '],
            ['id' => '115', 'name' => 'Nadëb'],
            ['id' => '116', 'name' => 'Nahukwá'],
            ['id' => '120', 'name' => 'Negarotê/ Negarote '],
            ['id' => '126', 'name' => 'Lingua Geral Amazônica, Nheengatu'],
            ['id' => '127', 'name' => 'Ninám'],
            ['id' => '128', 'name' => 'Nukiní'],
            ['id' => '129', 'name' => 'Ofayé'],
            ['id' => '130', 'name' => 'Oro Win'],
            ['id' => '131', 'name' => 'Palikúr'],
            ['id' => '132', 'name' => 'Panará, Krenakarôre/ Kren-akarôre'],
            ['id' => '133', 'name' => 'Paresí'],
            ['id' => '134', 'name' => 'Karipúna do Amapá'],
            ['id' => '135', 'name' => 'Galibí Marwórno/ Galibi Marworno'],
            ['id' => '136', 'name' => 'Paumarí'],
            ['id' => '137', 'name' => 'Pirahã'],
            ['id' => '138', 'name' => 'Piratapúya'],
            ['id' => '140', 'name' => 'Poyanáwa'],
            ['id' => '141', 'name' => 'Puruborá'],
            ['id' => '142', 'name' => 'Canoeiros/ Rikbaktsá'],
            ['id' => '143', 'name' => 'Sabanê'],
            ['id' => '145', 'name' => 'Enawenê-Nawê'],
            ['id' => '146', 'name' => 'Sanumá'],
            ['id' => '148', 'name' => 'Zuruwahá, Suruahá (Zuruahá]'],
            ['id' => '150', 'name' => 'Suyá, Kisêdjê/ Kisedjê'],
            ['id' => '151', 'name' => 'Tapirapé'],
            ['id' => '152', 'name' => 'Tariána'],
            ['id' => '153', 'name' => 'Taulipáng'],
            ['id' => '155', 'name' => 'Tembé'],
            ['id' => '156', 'name' => 'Teréna'],
            ['id' => '157', 'name' => 'Tikúna'],
            ['id' => '167', 'name' => 'Tiriyó/ Tarona '],
            ['id' => '168', 'name' => 'Torá'],
            ['id' => '169', 'name' => 'Trumái'],
            ['id' => '171', 'name' => 'Tuparí'],
            ['id' => '172', 'name' => 'Tuyúca / Tuyuca'],
            ['id' => '173', 'name' => 'Ikpeng/ Ikpéng'],
            ['id' => '174', 'name' => 'Tsohom Djapa/ Tsohondjapá (Tsohom Djapa]'],
            ['id' => '175', 'name' => 'Urupá'],
            ['id' => '176', 'name' => 'Waimirí-Atroarí'],
            ['id' => '177', 'name' => 'Wái Wái/ Waiwái'],
            ['id' => '178', 'name' => 'Wanána/ Guanána'],
            ['id' => '179', 'name' => 'Wapixána'],
            ['id' => '180', 'name' => 'Warekéna'],
            ['id' => '182', 'name' => 'Wauja/ Waurá '],
            ['id' => '183', 'name' => 'Wayampí/ Oyampi'],
            ['id' => '184', 'name' => 'Wayána'],
            ['id' => '185', 'name' => 'Xambioá'],
            ['id' => '186', 'name' => 'Xetá'],
            ['id' => '187', 'name' => 'Xipáya'],
            ['id' => '188', 'name' => 'Xokléng'],
            ['id' => '190', 'name' => 'Yanomám/ Yanonmán'],
            ['id' => '191', 'name' => 'Yanomámi'],
            ['id' => '192', 'name' => 'Fulni-ô/ Yathê'],
            ['id' => '193', 'name' => 'Yawalapití'],
            ['id' => '194', 'name' => 'Yawanawá'],
            ['id' => '196', 'name' => 'Zo\'é'],
            ['id' => '197', 'name' => 'Zoró'],
            ['id' => '198', 'name' => 'Akuntsú'],
            ['id' => '199', 'name' => 'Amondáwa'],
            ['id' => '200', 'name' => 'Arara do Aripuana/ Arara do Aripuanã'],
            ['id' => '201', 'name' => 'Arara do Pará, Arara do Xingu '],
            ['id' => '203', 'name' => 'Barasána'],
            ['id' => '204', 'name' => 'Kambéba'],
            ['id' => '205', 'name' => 'Kanéla Rankocamekra/ Canela Ramkokamekrã'],
            ['id' => '206', 'name' => 'Chamakóko/ Samúko, Chamacoco'],
            ['id' => '207', 'name' => 'Chiquitáno/ Chiquito'],
            ['id' => '208', 'name' => 'Diahói/ Diahui'],
            ['id' => '211', 'name' => 'Guajajára'],
            ['id' => '215', 'name' => 'Júma/ Juma'],
            ['id' => '216', 'name' => 'Yurutí, Juriti'],
            ['id' => '218', 'name' => 'Kapon Patamóna/ Kapon Ptamóna'],
            ['id' => '219', 'name' => 'Karipúna'],
            ['id' => '220', 'name' => 'Kayapó'],
            ['id' => '221', 'name' => 'Mebengokré (Kayapó]'],
            ['id' => '222', 'name' => 'Kinikináu, Kinikinawa'],
            ['id' => '223', 'name' => 'Kreje/ Krenjé'],
            ['id' => '224', 'name' => 'Krikatí/ Krinkatí'],
            ['id' => '225', 'name' => 'Kujubím'],
            ['id' => '226', 'name' => 'Kuripáko'],
            ['id' => '227', 'name' => 'Kwazá'],
            ['id' => '228', 'name' => 'Lakondê'],
            ['id' => '229', 'name' => 'Latundê'],
            ['id' => '230', 'name' => 'Mamaindê'],
            ['id' => '231', 'name' => 'Mandúka/ Nambikwára do Campo'],
            ['id' => '233', 'name' => 'Miránha'],
            ['id' => '234', 'name' => 'Tukáno / Miriti-Tapuia'],
            ['id' => '235', 'name' => 'Kaingáng'],
            ['id' => '236', 'name' => 'Suruí de Rondônia'],
            ['id' => '237', 'name' => 'Parakanã'],
            ['id' => '238', 'name' => 'Parintintín'],
            ['id' => '240', 'name' => 'Gavião Pukobiyé/ Gavião Pukobié'],
            ['id' => '241', 'name' => 'Tapayúna'],
            ['id' => '242', 'name' => 'Tawandê'],
            ['id' => '243', 'name' => 'Tenharím/ Tenharim'],
            ['id' => '244', 'name' => 'Umutína'],
            ['id' => '245', 'name' => 'Pakaá Nóva/Migueleno, Miguelenho'],
            ['id' => '246', 'name' => 'Shanenáwa/ Xanenáwa, Xawanawa'],
            ['id' => '250', 'name' => 'Tupí, Tupi Antigo '],
            ['id' => '251', 'name' => 'Canela'],
            ['id' => '252', 'name' => 'Kanéla Apaniekra/Canela Apaniekrã'],
            ['id' => '253', 'name' => 'Gavião Krikatêjê/ Gavião Krinkatejé'],
            ['id' => '254', 'name' => 'Gavião Parkatêjê/ Guató Parakatejé/ Gavião do Pará '],
            ['id' => '255', 'name' => 'Krahô/ Crao, Kraô'],
            ['id' => '256', 'name' => 'Krao Kanela'],
            ['id' => '257', 'name' => 'Kokuiregatêjê/ Kokuiregatejje '],
            ['id' => '258', 'name' => 'Timbira'],
            ['id' => '259', 'name' => 'Xacriabá/ Xakriabá'],
            ['id' => '260', 'name' => 'Jê (não específico]'],
            ['id' => '261', 'name' => 'Pataxó'],
            ['id' => '262', 'name' => 'Pataxó Hã Hã Hãe/ Pataxó Há-Há-Há'],
            ['id' => '263', 'name' => 'Salamãy'],
            ['id' => '264', 'name' => 'Ramaráma'],
            ['id' => '265', 'name' => 'Urucú/ Urucu'],
            ['id' => '266', 'name' => 'Guaraní'],
            ['id' => '267', 'name' => 'Lingua De Sinais Ka\'apor/ Língua de Sinais Urubu-Kaapór'],
            ['id' => '268', 'name' => 'Kawahíb'],
            ['id' => '269', 'name' => 'Turiwára'],
            ['id' => '270', 'name' => 'Tupí-Guaraní'],
            ['id' => '271', 'name' => 'Kaixána/ Kayuisiana'],
            ['id' => '272', 'name' => 'Machinéri'],
            ['id' => '273', 'name' => 'Mawayána'],
            ['id' => '274', 'name' => 'Aruák'],
            ['id' => '275', 'name' => 'Naravúte'],
            ['id' => '276', 'name' => 'Kaxuyána/ Kahyána, Warikyána'],
            ['id' => '277', 'name' => 'Xikuyána/ Sikiyána'],
            ['id' => '278', 'name' => 'Karib'],
            ['id' => '279', 'name' => 'Kulína Páno'],
            ['id' => '280', 'name' => 'Pano'],
            ['id' => '281', 'name' => 'Makúna, Yebá-masã'],
            ['id' => '282', 'name' => 'Siriáno/ Suriana, Suriána'],
            ['id' => '283', 'name' => 'Arawá'],
            ['id' => '284', 'name' => 'Himarimã/ Hi-merimã, Mirimã, Himarimá'],
            ['id' => '285', 'name' => 'Jamamadí-Kanamanti/ Jamamadí'],
            ['id' => '286', 'name' => 'Hup, Húpda, Maku, Yuhupde, Yuhúp'],
            ['id' => '287', 'name' => 'Alaketesú '],
            ['id' => '288', 'name' => 'Alantesú'],
            ['id' => '289', 'name' => 'Hahaintesú'],
            ['id' => '290', 'name' => 'Halotesú'],
            ['id' => '291', 'name' => 'Kithaulú'],
            ['id' => '292', 'name' => 'Sararé'],
            ['id' => '300', 'name' => 'Sawentesú'],
            ['id' => '301', 'name' => 'Waikisú'],
            ['id' => '302', 'name' => 'Wakalitesú'],
            ['id' => '303', 'name' => 'Wasusú'],
            ['id' => '304', 'name' => 'Nambikwára'],
            ['id' => '305', 'name' => 'Miguelénho/ Migueleno, Miguelenho'],
            ['id' => '306', 'name' => 'Txapakúra'],
            ['id' => '307', 'name' => 'Bóra'],
            ['id' => '308', 'name' => 'Guaikurú'],
            ['id' => '309', 'name' => 'Witóto'],
            ['id' => '310', 'name' => 'Acona/ Akona'],
            ['id' => '311', 'name' => 'Aimoré'],
            ['id' => '312', 'name' => 'Anacé'],
            ['id' => '313', 'name' => 'Apolima - Arara'],
            ['id' => '314', 'name' => 'Arana'],
            ['id' => '315', 'name' => 'Arapiun'],
            ['id' => '316', 'name' => 'Arikén'],
            ['id' => '317', 'name' => 'Arikose'],
            ['id' => '318', 'name' => 'Atikum'],
            ['id' => '319', 'name' => 'Awi'],
            ['id' => '320', 'name' => 'Baenã'],
            ['id' => '321', 'name' => 'Borari'],
            ['id' => '322', 'name' => 'Botocudo'],
            ['id' => '323', 'name' => 'Catokin (Katukína]'],
            ['id' => '324', 'name' => 'Charrúa/ Charrua'],
            ['id' => '325', 'name' => 'Coiupanka'],
            ['id' => '326', 'name' => 'Guara'],
            ['id' => '327', 'name' => 'Guarino'],
            ['id' => '328', 'name' => 'Guaru'],
            ['id' => '329', 'name' => 'Isse'],
            ['id' => '330', 'name' => 'Jaricuna'],
            ['id' => '331', 'name' => 'Jeripancó/ Jeripankó'],
            ['id' => '332', 'name' => 'Kaete'],
            ['id' => '333', 'name' => 'Kaimbé'],
            ['id' => '334', 'name' => 'Kalabassa'],
            ['id' => '335', 'name' => 'Kalankó'],
            ['id' => '336', 'name' => 'Kamba/ Kámba'],
            ['id' => '337', 'name' => 'Kambiwá'],
            ['id' => '338', 'name' => 'Kambiwá Pipipã'],
            ['id' => '339', 'name' => 'Kanindé'],
            ['id' => '340', 'name' => 'Kantaruré'],
            ['id' => '341', 'name' => 'Kapinawá'],
            ['id' => '342', 'name' => 'Karapoto/ Karapotó'],
            ['id' => '343', 'name' => 'Karijo'],
            ['id' => '344', 'name' => 'Kariri/ Karirí'],
            ['id' => '345', 'name' => 'Kariri - Xocó/ Karirí-Xocó'],
            ['id' => '346', 'name' => 'Kaxixó'],
            ['id' => '347', 'name' => 'Kayuisiana -(Kaixána]'],
            ['id' => '348', 'name' => 'Kiriri'],
            ['id' => '349', 'name' => 'Kueskue'],
            ['id' => '350', 'name' => 'Manao/ Manáo'],
            ['id' => '351', 'name' => 'Maragua'],
            ['id' => '352', 'name' => 'Maytapu'],
            ['id' => '353', 'name' => 'Mucurim'],
            ['id' => '354', 'name' => 'Nawa/ Náwa'],
            ['id' => '355', 'name' => 'Paiaku'],
            ['id' => '356', 'name' => 'Pankará'],
            ['id' => '357', 'name' => 'Pankararé'],
            ['id' => '358', 'name' => 'Pankararú/ Pankarú'],
            ['id' => '359', 'name' => 'Pankararú - Kalanko'],
            ['id' => '360', 'name' => 'Pankararú - Karuazu'],
            ['id' => '361', 'name' => 'Pankaru'],
            ['id' => '362', 'name' => 'Patxôhã/ Patxoha'],
            ['id' => '363', 'name' => 'Paumelenho'],
            ['id' => '364', 'name' => 'Piri-Piri/ Pirí-Pirí'],
            ['id' => '365', 'name' => 'Pitaguari/ Pitaguarí'],
            ['id' => '366', 'name' => 'Potiguara/ Potiguára'],
            ['id' => '367', 'name' => 'Puri/ Purí'],
            ['id' => '368', 'name' => 'Sapará/ Sapara'],
            ['id' => '369', 'name' => 'Tabajara'],
            ['id' => '370', 'name' => 'Tapajós'],
            ['id' => '371', 'name' => 'Tapeba'],
            ['id' => '372', 'name' => 'Tapiuns/ Tapiun'],
            ['id' => '373', 'name' => 'Tapuía/ Tapúya'],
            ['id' => '374', 'name' => 'Tingui Botó/ Tinguí-Botó'],
            ['id' => '375', 'name' => 'Tremembé'],
            ['id' => '376', 'name' => 'Truká'],
            ['id' => '377', 'name' => 'Tumbalalá'],
            ['id' => '378', 'name' => 'Tupinambá'],
            ['id' => '379', 'name' => 'Tupinambaraná'],
            ['id' => '380', 'name' => 'Tupiniquim'],
            ['id' => '381', 'name' => 'Tuxá'],
            ['id' => '382', 'name' => 'Waira'],
            ['id' => '383', 'name' => 'Waiána-Apalaí'],
            ['id' => '384', 'name' => 'Wajuju/ Wajujú'],
            ['id' => '385', 'name' => 'Wassú (Wasusú]'],
            ['id' => '386', 'name' => 'Xocó'],
            ['id' => '387', 'name' => 'Xucuru/ Xukurú'],
            ['id' => '388', 'name' => 'Xucuru - Kariri/ Xukurú-Karirí'],
            ['id' => '389', 'name' => 'Maya'],
            ['id' => '999', 'name' => 'Outras Linguas Indigenas']
        ]);
    }
}
